### ISSUE TITLE
verify commands

### ISSUE THREAD

**Issue by babuto00** [SeleniumHQ/selenium-ide#102]
Hello, will more verify type commands be available in any future release - such as verifyElementPresent etc? Further - I also miss waitForPageToLoad, will that be available as well? Thanks for reply.

**Comment by corevo** [comment]
`verifyElementPresent` is something we'll gladly bring back,  
`waitForPageToLoad` is unnecessary anymore, as the IDE waits automatically for you, if you need extra waiting you can use the `pause` command.

**Comment by babuto00** [comment]
Ok, it thought so with the waitForPageToLoad. Thank you so much!

**Comment by corevo** [comment]
I didn't manage to add this to today's release, but it'll be added soon

**Comment by olds97lss** [comment]
The waitforpagetoload command is nice due to some sites taking more time than expected to load, you can manually define the wait time. Having a static pause doesn't work as well. I currently use waitforvisible a lot as well on pages that load, but you need to wait for a specific element to render before continuing.
