### ISSUE TITLE
selenium-side-runner output for Nagios

### ISSUE THREAD

**Issue by romsworld** [SeleniumHQ/selenium-ide#1021]
## 🚀 Feature Proposal

Hi,

Is it possible to have output for Nagios, with perfdata

## Motivation

Best way to implementation for monitoring with selenium !

## Example

selenium-side-runner -s http://localhost:4444/wd/hub --output-nagios
OK: Passed 1 of 1 tests. | 'passed'=1;;;; 'failed'=0;;;; 'exec_time'=6s;;;;

this solution exist, but it was not the best way https://github.com/opsdis/check_selenium_docker#execute-the-plugin

Thanks !

**Comment by corevo** [comment]
This sounds like a plugin for Selenium IDE, rather than something that we should support & maintain first party, we currently have plugins available for Selenium IDE, they may be a bit more limited in the runner, but perhaps possible to do what you need.

I'm glad that someone in the community wrote a solution for this, I'd be happy to go over potential changes to our Plugin API in order to accommodate the use-case, but this will have to be included as a plugin rather than first party.

If you could lay out exactly what you need from the Plugin API in order to write this integration we can discuss that.

**Comment by romsworld** [comment]
Thanks for answer.

In fact, I need a simple solution to supervise websites.
Selenium IDE can generate .side files.
The Side runner makes it easy to launch the project.

I need to be able to run the test through nagios or fork and retrieve the result with the standard nagios error codes ok, warn, crit, unkn, and also perfdatas, (execution time e.g.).

Maybe there is another solution?

**Comment by corevo** [comment]
So what I could recommend you build is something that would parse the output of the runner and send it to whatever monitoring system you need, the solution you've sent works on the text output of the runner, maybe a better solution would be to parse the [output file](https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner#output-test-results-to-a-file)

**Comment by romsworld** [comment]
I can do that, but it adds an extra layer. A script that launches side runner, and it parse. I find it heavy.
The output for nagios is the same since 30 years :) !

**Comment by corevo** [comment]
It has nothing to do with nagios specifically, anything we put directly into the runner will cause 2 things:

- we the selenium team will have to support it
- it creates a precedent, and we won't include ootb integration with all the monitoring systems out there, it'll never end

To sum up, it is out of scope.

What I suggest you do is one of the following
- write a plugin for the runner, then it wouldn't be another layer, I'd be happy to help design the runner end of things with you
- do it from the outside, it will add another layer, but you don't need us to do it

**Comment by AutomatedTester** [comment]
Closing as this is out of scope for this project.
