### ISSUE TITLE
It takes too long to build

### ISSUE THREAD

**Issue by etyero** [SeleniumHQ/selenium-ide#1054]
It takes too long to build

![image](https://user-images.githubusercontent.com/26212853/82869587-15867980-9f61-11ea-8428-ae0358105ef9.png)

**Comment by tourdedave** [comment]
~16 seconds seems reasonable given that it's building production versions for multiple browser extension platforms. Also, you only build the production task when it's time to cut a release. Otherwise, you'd use `yarn watch` which would build much more quickly and do incremental builds based on local changes.

Closing.

Although, I am curious -- "too long" compared to what? Any recommendations for how to improve the build time?

**Comment by etyero** [comment]
> ~16 seconds seems reasonable given that it's building production versions for multiple browser extension platforms. Also, you only build the production task when it's time to cut a release. Otherwise, you'd use `yarn watch` which would build much more quickly and do incremental builds based on local changes.
> 
> Closing.
> 
> Although, I am curious -- "too long" compared to what? Any recommendations for how to improve the build time?

emmm...it's not 16 seconds ,it's 160 seconds

**Comment by tourdedave** [comment]
Ah, I see. Well, 2 minutes then.

Still, the other comments hold true. The production build task is meant as a seldom used task.

If you are experiencing overall slow build times even with incremental builds then please open a new ticket and __follow the issue template__.

**Comment by corevo** [comment]
A production build does take a lot of time, and it is around the time I would assume it would take.

Some of the processes that run during build are
 - Uglify
 - Minify
 - Babel transpilation
 - Google closure compiler

And the closure compiler specifically is implemented both in js and java, we use the js version which is considerably slower because we don't want users to have to install java.

If you want you can change the webpack config to use java and choose based on wether the user has or doesn't have java.

**Comment by etyero** [comment]
> Ah, I see. Well, 2 minutes then.
> 
> Still, the other comments hold true. The production build task is meant as a seldom used task.
> 
> If you are experiencing overall slow build times even with incremental builds then please open a new ticket and **follow the issue template**.

ok，thanks

> A production build does take a lot of time, and it is around the time I would assume it would take.
> 
> Some of the processes that run during build are
> 
> * Uglify
> * Minify
> * Babel transpilation
> * Source mappings
> * Google closure compiler
> 
> And the closure compiler specifically is implemented both in js and java, we use the js version which is considerably slower because we don't want users to have to install java.
> 
> If you want you can change the webpack config to use java and choose based on wether the user has or doesn't have java.

Got it, thanks
