### ISSUE TITLE
NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

### ISSUE THREAD

**Issue by bianyucheng-eb** [SeleniumHQ/selenium-ide#1064]
## 💬 Questions and Help

When I use selenium-side-runner for testing, the following error occurs

```
`NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

      at ../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/webdriver.js:729:38
      at Object.thenFinally [as finally] (../../usr/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/promise.js:124:12)
      at WebdriverEnvironment.global.cleanup (../../usr/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:30:7)
celeryworker_1       | 
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        320.123s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to tr
  `
```
This error does not necessarily happen, I wonder if it is due to timeout?

**Comment by tourdedave** [comment]
The questions and help template you used states:

`Please note that this issue tracker is not a help form and this issue will be closed.`

If you are able to provide a way for us to reproduce the issue, then please open a `Bug Report` issue with specifics.

Otherwise you can ask for help in the following places:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group
