### ISSUE TITLE
Adding comments is not available in new selenium IDE

### ISSUE THREAD

**Issue by manikumary** [SeleniumHQ/selenium-ide#107]
hi,
We have a feature of adding comments in the steps which help to understand the steps easily by anyone when script steps are more.
In new IDE please consider feature of adding comments. (like  when we include //  followed by text is considered as comment Ex: //test for login)
Also consider while migration of old selenium tests to new ide. if any old tests have comments those should be visible in new IDE as well.

**Comment by corevo** [comment]
I understand the importance of comments,  
But I'm not sure this is the best way to go, as the space in the table is limited, and this info has nothing to do with the data itself, it is just a metadata.  
I will try to find a better way to do this, when I have that solution I will make sure to migrate the comments as well.

**Comment by manikumary** [comment]
ok thanks for your reply.

**Comment by generalov** [comment]
Testing frameworks often display test scenarios as compact and human readable specs.
<img src="https://raw.githubusercontent.com/bcaudan/jasmine-spec-reporter/HEAD/screenshot.gif"  width=100>

The [SnapTest](https://chrome.google.com/webstore/detail/snaptest/aeofjocnhdlleichkjbaibdbicpcddhp) extension uses the similar approach in GUI. It just display comments on the front of steps implementation details.
<img src="https://s9.postimg.org/yib2wd0fz/emulate.png" width=100> <img src="https://s9.postimg.org/4ewk4ex6n/manage.png" width=100> <img src="https://s9.postimg.org/kyu8qnmgv/configure.png" width=100>

What if Selenium IDE  implements something like that? 
<img src="https://s17.postimg.org/n87xgz6wf/005.png" width=300>

**Comment by corevo** [comment]
Amazing idea, I'm working on it right now

**Comment by corevo** [comment]
@manikumary I will need an example from the old IDE of comments, from my understanding there are two types.
 - comment that can be inserted through context menu
 - comment that you can add as you described
If you could give me an example test case I'd gladly work on migrating those

**Comment by corevo** [comment]
I'm gonna accept the PR, if you have an example later on, post it here and I'll work on a migration

**Comment by sasivimala** [comment]
After reading this web site I am very satisfied simply because this site is providing comprehensive knowledge for you to audience. 
Thank you to the perform as well as discuss anything incredibly important in my opinion. We loose time waiting for your next article writing in addition to I beg one to get back to pay a visit to our website in


<a href="http://www.trainingbangalore.in/selenium-training-in-bangalore.html">Selenium training in bangalore </a>  
<a href="https://www.besanttechnologies.com/training-courses/software-testing-training/selenium-training-institute-in-chennai">Selenium training in Chennai </a>
