### ISSUE TITLE
Selenium IDE Chrome extensions breaks Photopea by predefining window.confirm

### ISSUE THREAD

**Issue by olegivashko** [SeleniumHQ/selenium-ide#1100]
## 🐛 Bug Report

I have a Photopea and your extension breaks it by predefining window.confirm
See this issue for more reference - https://github.com/photopea/photopea/issues/2322#issuecomment-663589699.

Decided not to write a negative review for you guys as you did a great job with your extension. 
However I had to disable your extension on my Chrome for now.
Hope this bug will get fixed soon.

## To Reproduce

* Have your extension active
* Go to https://www.photopea.com/
* Open any JPG file
* Get error as described here https://github.com/photopea/photopea/issues/2322#issuecomment-663589699

## Expected behavior

Photopea opens the JP file with no error

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: macOS Catalina 10.15.6
Selenium IDE Version:  have no idea
Selenium SIDE Runner Version:  have no idea
Node version: have no idea
Browser: Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by corevo** [comment]
I'm not sure how does a negative review would help, opening an issue is a much more effective way to give us the information to solve bugs, as we can communicate back and forth together.

Currently that patch is required for us to be able to record confirm, and we need to place it in advanced so you can record without having to refresh the browser.

What this means is that Selenium IDE will never be able to record Photopea, a reasonable solution would be to add an exclusion list of webpages where you want Selenium IDE to be disabled, that way you can keep using Selenium IDE and Photopea.

But I also think that this could be a low priority, because once we move to electron, then websites that do not work with Selenium IDE will not work with it regardless, and you'll have to use a browser, what I mean is that when you use Selenium IDE you use it for 2 use-cases, casual browsing and recording, moving to electron will remove the casual browsing, which will remove the use-case.

**Comment by toddtarsi** [comment]
Not an issue in v4, which uses a dedicated Electron browser for recording.
