### ISSUE TITLE
Issue handling &quot; from old ide scripts

### ISSUE THREAD

**Issue by bryanl-csi** [SeleniumHQ/selenium-ide#114]
It appears version 1.0.3 has an issue with how old selenium id stored the html equivilant to quotes for locators.

`css=input[name=&quot;login&quot;]`

![2018-0227-v1 0 3-issuewithquotes](https://user-images.githubusercontent.com/883039/36736953-76bf8f2c-1b9f-11e8-8252-d3e6123cb772.png)

**Comment by corevo** [comment]
It is a side effect of a new compatibility fix for old Selenium test cases that I will fix.

**Comment by olds97lss** [comment]
With that in mind, I'm noticing that the new IDE is showing the <title>text</title> on the left side whereas the old ide appeared to just show the file name without the .html. I'm assuming that will continue to be honored?

If so, I'll have to update all my scripts as very few of them have a title that matches what they really are as they are copies of copies and since I never had to care, I  never bothered changing the tag in the script. I always just made the file name be something relevant.

**Comment by corevo** [comment]
I understand, I'll have to look into it, because this behavior needs to represent what most will like.

**Comment by corevo** [comment]
Can you send me the `html` for testing?

**Comment by bryanl-csi** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://change-this-to-the-site-you-are-testing/" />
<title>CreateTMOrder-927</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">CreateTMOrder-927</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>https://www.compusystems.com/jsp/Catalog/Index.jsp?show_list=927</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>css=input[name=&quot;login&quot;]</td>
	<td>XXXX</td>
</tr>
</tbody></table>
</body>
</html>
`
