### ISSUE TITLE
Export to Django Live Server Format

### ISSUE THREAD

**Issue by mkalioby** [SeleniumHQ/selenium-ide#1145]
## 🚀 Feature Proposal

Django (Web Framework for Python) has a selenium driver that avoids starting the HTTP Server for selenium to run, Django start the server on a random port and the address is available in the test class.

Refer to [Django Live Server](https://docs.djangoproject.com/en/2.2/topics/testing/tools/#liveservertestcase)

## Motivation

The format is so close to PyTest, only minor modifications are required and the developers can create their test cases by Selenium IDE and export to Django Server format then run the tests by 

`python manage.py test` 

without starting the http server, which is much easier for CI pipelines.

**Comment by corevo** [comment]
We strictly only provide support for first party (or most common) test framework in each supported language, that is to limit both maintenance of the project, and to prevent creating a precedent where we would write an export for every setup available.

Because of that we've created plugins, I highly suggest writing this as a plugin for Selenium IDE, as we will not accept this PR.

**Comment by mkalioby** [comment]
Thanks for your reply.

Can you direct me for the plugin documentation?

Thanks in advance.

**Comment by corevo** [comment]
Of course, its available with the rest of the docs on the [official webpage](https://www.selenium.dev/selenium-ide/docs/en/plugins/code-export).
