### ISSUE TITLE
Upload a file

### ISSUE THREAD

**Issue by Eggroll9000** [SeleniumHQ/selenium-ide#120]
Add ability to upload a file

Previously, uploading a file was:
Command: type
Target (xpath/css): data.upload.whatever
Value (file path): /users/foo/bar/file.png

Now it doesn't work and gives an error:
Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

**Comment by corevo** [comment]
I'm afraid that's currently impossible,  
The new extension standard doesn't allow filesystem access, to protect users.

**Comment by carmiadam** [comment]
Cant you simulate it somehow? Serialize the file as part of the project?

**Comment by corevo** [comment]
I can add a file upload, and save it as base64 as part of the project,  
I'll also need to add some kind of file management view to delete old files.

**Comment by Eggroll9000** [comment]
Not being able to upload a file would be a disaster. Countless tests involve uploading an image or a video such as a profile image or album or youtube video.

**Comment by idefix1** [comment]
The [Kantu Selenium IDE](https://github.com/A9T9/Kantu-for-Chrome) _can_ upload files, see https://a9t9.com/kantu/docs/webextensions#fileupload

**Comment by Jongkeun** [comment]
@idefix, He said he can, but didn’t want.

**Comment by idefix1** [comment]
@Jongkeun Ah, yes, I missed that.

**Comment by corevo** [comment]
We threw a few ideas at the office,
I’ve found a workaround for chrome, but it doesn’t work on Firefox.

Cheers,
Tom

**Comment by corevo** [comment]
Just here to update, I'm working on it for Chrome,  
Firefox might take a bit longer because the same method doesn't work for it.  
I'm gonna look for a way to bring file upload to both.  
Anyway like Kantu, using this workaround I won't be able to recreate the path the file was uploaded from, and you'll have to reenter it.

**Comment by corevo** [comment]
We have a way to get this working on Chrome,  
In playback it's gonna work on Chrome, and once we change the playback to work on top of webdriver instead of selenium core, we'll ship it to Firefox as well.  
Just to note, we're gonna finish up working on running in CI on top of webdriver as well, which we will support file upload in too, so that you can use it with firefox that way.

**Comment by jasetom** [comment]
Thank you. I'm waiting for this to be shipped to the selenium ide chrome extension!

**Comment by Eggroll9000** [comment]
I'm running the current release in Chrome from April (after Mar 13) and there does not appear to be a way to upload a file. I'm looking for commands like "get file" or "upload file" and don't see any.

**Comment by corevo** [comment]
Just like in Selenium, use:  
`type | locator to input[type="file"] | /path/to/the/file.png`

**Comment by kwmtang** [comment]
This still does not work on the latest Chrome. Has anyone actually tried this?

**Comment by corevo** [comment]
This test is ran daily, and confirmed working.  
@kwmtang Yes people test this and try this.
![aug-01-2018 11-06-22](https://user-images.githubusercontent.com/888886/43509308-fe86eebe-957a-11e8-905b-ce79f20e5f16.gif)

**Comment by corevo** [comment]
But this isn't a selenium command (hehe), webextensions don't support selenium file uploads, instead we are using Chrome debugging protocol, that only supports query selectors.

**Comment by kwmtang** [comment]
This is gotta be a P0 blocker. How can Selenium IDE be expected to survive without this feature? My devs almost never have the time to make ids with all the crazy fields and buttons that need to be made every sprint and QA makes do with whatever crazy fragile xpaths we can use. We are able to keep up because IDE is so much faster to write than our TestNG and RobotFramework tests. Can we escalate this somehow? This is a mission critical feature. Any testing of a modern site/app will normally include uploading images, documents, audio, and video files.

**Comment by corevo** [comment]
You are more than welcome to send a pr.  
At this moment all commands support xpath except file uploading, this situation is temporary, but the dev team believes other things are *mission critical*.  
As I said, the code relevant to the issue is [here](https://github.com/SeleniumHQ/selenium-ide/blob/master/packages/selenium-ide/src/neo/IO/debugger.js#L76), we will greatly appreciate a contribution.

**Comment by zavelevsky** [comment]
@kwmtang don't get the wrong impression - xpaths can be used for all commands, except for file upload. You wrote: 

> My devs almost never have the time to make ids with all the crazy fields and buttons that need to be made every sprint and QA makes do with whatever crazy fragile xpaths we can use

So yes, they can keep working this way, but they'll have to use a query selector specifically for file uploads. We have a few ideas how to improve that, but there's a lot of work getting done and we have to prioritize. As @corevo said, you are very welcome to contribute. 

Does this answer you questions?

**Comment by p2635** [comment]
Hi all, I have tried 3.4.4 and this works in Chrome but it doesn't work in Firefox. Can someone help?

**Comment by corevo** [comment]
@p2635 correct this feature works only in Chrome, the reference tab states that, perhaps we can add an error message in Firefox that it is unavailable.

**Comment by p2635** [comment]
Thanks @corevo , I know it is not possible for Firefox currently but will there more development on this? It will be amazing if this is possible so my tests will both on Chrome and Firefox. Firefox will just have to be semi automated for now and I have to set a breakpoint at the point of file upload to manually intervene.

**Comment by corevo** [comment]
I'm sorry for the inconvenience, I can assure you, that if Firefox implements the required APIs to enable Selenium IDE's file uploads we will do so.

**Comment by tourdedave** [comment]
@p2635 Have you seen the command-line runner for Selenium IDE? You can run your tests on any browser with it.

https://www.seleniumhq.org/selenium-ide/docs/en/introduction/command-line-runner/

**Comment by p2635** [comment]
Hi @tourdedave, yes I have seen it but I decided not to use it after much exploration. There were so many inconsistencies with IDE, I had to modify my commands just to make it work with side runner. For example, variables that have '-' character throw an error. Also, the slash for file upload paths needs to be changed from backslash (\) to forward slash (/) in order to work. There are a few more but those are just some examples.

**Comment by hamzazar** [comment]
@corevo the upload file works fine in chrome when running tests with Selenium IDE but it fail when trying to run the test using Command-line Runner

`selenium-side-runner  lasource-upload.side 
info:    Running lasource-upload.side
 FAIL  ./Default Suite.test.js
  ● Test suite failed to run

    TypeError: Target browser must be a string, but is <undefined>; did you forget to call forBrowser()?

      at Builder.build (../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/index.js:574:13)
      at buildDriver (../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:65:17)
      at WebdriverEnvironment.setup (../../../usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-environment-selenium/dist/index.js:36:32)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.211s, estimated 10s
`

**Comment by corevo** [comment]
Try running `selenium-side-runner -c "browserName=chrome" lasource-upload.side`

**Comment by hamzazar** [comment]
Same result!

**Comment by twnew** [comment]
Is the file upload feature broken? I get 

```
type on id=image1 with value c:\test\u1.png Failed:
{“code”:-32000,“message”:“Not allowed”}
```

**Comment by corevo** [comment]
@twnew please refer to #569 
I'm locking this conversation as this feature was implemented, and further discussion should take place either in #569 or in a new issue if applicable.
