### ISSUE TITLE
Port Selenium IDE into a Web App (React + Node)

### ISSUE THREAD

**Issue by minhiu** [SeleniumHQ/selenium-ide#1242]
## 🚀 Feature Proposal

Port Selenium IDE into a Web App (React + Node)

## Motivation

We are a small company in Asia and we came up with an idea of porting Selenium IDE into a Web App using React and Node.js. We would like to ask if it's possible to create a webextension-polyfill instance using web app instead of an extension. We needed this because our company blocked users from using browser extension.

## Example

Create a server using Node.js to call browser API (if needed)

**Comment by toddtarsi** [comment]
@minhiu - We are in agreement here! Actually, v4 is intended to do pretty much  exactly this, but instead of a web-app, it will be a desktop app using electron! The reason for this is that electron is basically a Node server married to a chrome instance, and bundling in a binding like chromedriver is super easy and supported by the api this way.

**Comment by toddtarsi** [comment]
I'm going to close this as it has been on the books for years. It's actually rigged up to a project description here:

https://github.com/SeleniumHQ/selenium-ide/projects

Thank you for reporting, and hopefully someday soon we can get this out. Thanks!
