### ISSUE TITLE
selenium-side-runner  UnexpectedAlertOpenError

### ISSUE THREAD

**Issue by backit** [SeleniumHQ/selenium-ide#1270]
## UnexpectedAlertOpenError

Using selenium-side-runner to run a .side test made with firefox selenium extension. If the page tested contains an alert confirm handled with "choose ok on next confirmation", selenium-side-runner fail with UnexpectedAlertOpenError. With the firefox extension it succeeds.

This is the .side test file:
[testalert.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/7129118/testalert.side.txt)

The used command:
`selenium-side-runner testalert.side --timeout 2000 -c "browserName=firefox"`

The output:

UnexpectedAlertOpenError: Dismissed user prompt dialog: Press a button!

      at Object.throwDecodedError (../node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (../node_modules/selenium-webdriver/lib/http.js:486:26)

Selenium-side-runner installed via npm as per documentation:
`npm install -g selenium-side-runner`

Using:
firefox 91.02
on linux ubuntu 20.04 (but happen on debian 11 too)
node 10.19.0
selenium ide firefox extension 3.17.0
selenium-side-runner 3.17.0

NB: if i use "webdriver choose ok on visible confirmation" selenium-side-runner succeed but firefox extension fails.

**Comment by toddtarsi** [comment]
@backit - Ah, yes you're seeing one of the challenges of using selenium-IDE vs selenium-side-runner and why we want to go to v4 so bad!

Basically, selenium-IDE performs local playback via as a series of JS shims, which gets __really__ messy when you start dealing with things that halt the execution context like alerts. The "correct" way to do it is the version for the side-runner. That's actually using a driver to execute the simulated command and respond to the alert. The browser version is doing some really goofy things that are only okay because javascript is a mess.

v4 is going to soothe this because we will be conducting playback using these two contexts:

1. The correct way against an electron app (active playback / recording).
2. The correct way against a browser (side-runner, exported test, etc).

There will be so much less delta in how selenium has to operate that our tests can be so much more consistent.

In the meantime, I've "fixed" your script for now:

[testalertbutfixed.side.txt](https://github.com/SeleniumHQ/selenium-ide/files/7155346/testalertbutfixed.side.txt)

**Comment by toddtarsi** [comment]
I've closed this because the actual fix is going to be going to selenium-ide v4 when it is ready(*not Selenium v4, that is a WHOLE OTHER THING), but feel free to re-open if there is more you'd like to discuss or you feel like your issue wasn't adequately addressed. Thanks!
