### ISSUE TITLE
I want to onboard Selenium IDE to my current Investment Firm .Need help to get some answers  on security aspect 

### ISSUE THREAD

**Issue by nathdiptanu** [SeleniumHQ/selenium-ide#1315]
## 💬 Questions and Help

I am huge fan of Selenium IDE for Chrome .But to onboard it to an Investment Firm ,i work  ,would need some help in answering few questions w.r.t data privacy and usage .

1)What type of data is handled by the extension .Any PII data at risk ?
2)Does this plugin requires local PC port opening ?
3)Use of jars/library by the extension .Can we configure where from the extension should point for Selenium jars/Chrome binary?
4)Ask on damage potential :
    a)if attackers gain access to the plugin ,what's the worst situation that would arise
    b)if tampered data (steps recorded)is stored in storage for further use by users?
    c)Please measure impact incase of system compromise -(Reputation/Regulatory/Financial | High/Moderate/Low)
5)Can i restrict the plugin once onboarded to be used for specific domains  and environment alone .
6)Is there any enterprise edition available ?
7)If onboarded .Will there be any data the extension feeds to external world ?.
8)With newer versions of Chrome coming up ,will the extension stop working ?Can we change the dependent libraries ourselves .

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by toddtarsi** [comment]
It's probably good to have this in an issue thread actually because I get this a lot. Also, sorry for the delay. I started to reply to your email, but then some stuff came up and I got distracted and whatnot.

1.  Nothing except what is saved into test steps. (I doubt you're saving John Doe's PII into a test step)
2. This runs in a webextension, so no. All access is provided by active browser. If using playback via the selenium-side-runner, I don't think so, but that might be a question for the selenium core team.
3. If using the selenium-side-runner, yes. If using in-browser playback, also yes but its chosen by just installing the browser you want to use. 
4.
    1. Since we're a webextension using permissions for recording and playback, being compromised would be terrible. Compromising a webextension with the <all_urls> permission is basically equivalent to a malicious party watching everything you're doing in browser. Very, very bad. 
    2. Not so much of a concern. The malicious step replacement would mean a malicious party has already acquired those credentials. In addition, you shouldn't be running these automated tests in your production environment in the first place.
    3. All three could be quite high unfortunately. Quite bad.
5. Unfortunately not.
6. Absolutely not.
7. Absolutely not. All data is persisted only by saved tests and projects and the format is quite straightforward json. We don't use any tools for analytics or anything like that. It's 
8. Eventually, likely yes. We're actively working on v4, and then v3 will be shelved. It will run in Electron, so it will use the chromium rendering engine butted up to NodeJS.

The main security risk to the webextension is that a malicious party publishes a compromised version of a package used by selenium-ide, and abuses the elevated permissions to broadcast all of your browser events back to their systems. These will be greatly mitigated in v4 of the ide. Because the ide will be a standalone binary, we'll no longer be sharing an environment with your browser. There will still be the usual risks of a compromise to the binary, but generally things will be much more sandboxed this way. The target date for a beta is around April, so if this risk is a deal breaker for you, check back in around then and we may have enough of a skeleton up for you to try that system.

**Comment by nathdiptanu** [comment]
Thank you **toddtarsi** for providing a detailed overview of the extension .It really helps a lot in answering the queries .
I will take this back and discuss with security team on the onboarding process into firm .
Thank you again .

**Comment by nathdiptanu** [comment]
1 point to clarify 
3)Use of jars/library by the extension .Can we configure where from the extension should point for Selenium jars/Chrome binary?

Ans:If using the selenium-side-runner, yes. If using in-browser playback, also yes but its chosen by just installing the browser you want to use.

1 clarification ,i would be asking for import of the chrome extension from https://www.selenium.dev/selenium-ide/
Now ,for configuration of Selenium jars where to do the configuration or the browser while installation itself will take care of the jars getting used ?am i thinking the right way ?Any documentation on the same would really help .
