### ISSUE TITLE
Selenium IDE is getting stuck while clicking a drop down

### ISSUE THREAD

**Issue by avitalvolik** [SeleniumHQ/selenium-ide#1317]
## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

OS: 
Selenium IDE Version:  
Selenium SIDE Runner Version:  
Node version: 
Browser:
Browser Version:

**Comment by avitalvolik** [comment]
Hello, I'm having a problem where Selenium gets stuck when I try to click a dropdown while recording. This prevents me from continuing with the recording and forces me to restart from the beginning.
Please advise me on what I should do in this situation!

**Comment by toddtarsi** [comment]
Unfortunately, my current and most immediate goal is v4 of the IDE, which I'm aiming to get out around April. After that is out, I intend to come back around and revisit / triage more nuanced issues like this. I'm sorry if this affects your ability to perform your workflow, but its the best move I can make for the long term health of this tooling.

In addition, this information is insufficient to triage your issue. Generally, when clicking a dropdown fails, it's because of a bad selector. Best of luck and I hope you find a solution.

**Comment by toddtarsi** [comment]
@avitalvolik - v4 of the IDE is available to download here:

https://github.com/SeleniumHQ/selenium-ide/releases

Feel free to try it, and if it helps with your issue, great! If not, well feel free to re-open this. Thanks!
