### ISSUE TITLE
Command execute script 

### ISSUE THREAD

**Issue by fahdionic2** [SeleniumHQ/selenium-ide#1360]
Hi ,
I test alert(); wirth command execute script  in mozilla firefox  but not working.
please can you help me to fix this error

**Comment by toddtarsi** [comment]
@fahdionic2 - We are in the throes of moving to v4. Effectively, this occurs because we're trying to use simulated JS to polyfill the alert API so we can capture alert interactions. Once on v4, which will do local playback using a webdriver in Electron, and alerting can just be alerting.

Give us a couple weeks and we'll be hitting alpha.
That said, I would avoid creating alerts from execute script, seeing as alert fully blocks all JS thread execution.

**Comment by toddtarsi** [comment]
If you must though, it should work as expected in V4. Thank you for trying the IDE and reporting this issue! 😄

**Comment by fahdionic2** [comment]
any code js with command execute script not working in firefox mozzila, but in chrome working fine .
I think firefox who block execute script JS .

**Comment by toddtarsi** [comment]
Closing this as I've basically given up on v3
