### ISSUE TITLE
Is there any support for map navigation in Selenium IDE?

### ISSUE THREAD

**Issue by ezequias** [SeleniumHQ/selenium-ide#161]
Hi everyone

I would like to know if there is any support for map navigation (Google Maps, Esri Maps) on Selenium IDE?

Is there any configuration that could be done to do this properly?

Regards
Ezequias

**Comment by corevo** [comment]
At this time there is no specific framework commands, it can be achieved later when plugins will be a thing, you could create specific commands for google maps.  
Right at this time, since it is a webapp, I'd try to use the same tools the IDE provides, using drag to pan the map, and clicks, you can use `click at` to click at a specific coordinates.
