### ISSUE TITLE
Selenium IDE 4 - problem with variables through different test cases

### ISSUE THREAD

**Issue by alevolpi85** [SeleniumHQ/selenium-ide#1633]
Hi all,
I have troubles with using variables through test cases; this is the situation:
I run a Test suite with "Test case 1" and "Test case 2".
I stored a value in myVar in "Test case 1", and echoing it I can see the value.
When I use ${myVar} in "Test Case 2", it's empty.

I used Selenium IDE 4 on my pc, with Windows 10 Pro, for some weeks and everything works fine.
My company configured a new fresh virtual machine and I get the problem described.
On this VM there is Windows Server 2019 Datacenter.
Can this be the problem? There is some incompatibility?
The latest version of Chrome is installed.
Do I have to install anything else?

Thanks for your time and help.

**Comment by toddtarsi** [comment]
Variables shouldn't work like that. Something declared in test A should never be set in test B. I believe test isolation in jest (our underlying runner) would not allow that.

If you do need to do this, you can probably make a third test that runs the other two tests back to back via the 'run' command. I think variables would be persisted then because you're in one root "test" this way

**Comment by alevolpi85** [comment]
You are definitely right!
Without seeing my code and what I've done, you hit the spot.
On my PC I created an extra test with "run" command to loop on Test cases.
On the VM not yet and this is the point.
Thanks a lot for the support and the work you are doing!
