### ISSUE TITLE
SeleniumIDE can't receive payload of record command from external WebExtension

### ISSUE THREAD

**Issue by vbaulac** [SeleniumHQ/selenium-ide#1683]
Hello,

I'm trying to add some custom command using my homemade plugin like the documentation say we can: https://www.selenium.dev/selenium-ide/docs/en/plugins/plugins-getting-started

It is working fine, I am registering my plugin with my command like that 
```

const registerPayload = {
            uri: "/register",
            verb: "post",
            payload: {
              name: "InterceptPOC",
              version: "1.0",
              commands: [
                {
                  id: "threeJsCommand",
                  name: "ThreeJS Action"
                } 
                ]
            }
          };

          chrome.runtime.sendMessage("mooikfkahbdckldjjndioackbalphokd", registerPayload);
```
And I can see my command on my IDE :
![image](https://github.com/SeleniumHQ/selenium-ide/assets/18035861/d54eb9fd-33f5-4ed8-a5df-3d4c7a5b6c99)

But when I try to do a post when I record, with 
```
const requestPayload = {
        uri: "/record/command",
        verb: "post",
        command: "threeJsCommand",
        target: "test"
      }

      chrome.runtime.sendMessage("mooikfkahbdckldjjndioackbalphokd", requestPayload);
```

**I do receive something, but it is blank and commented.**
![image](https://github.com/SeleniumHQ/selenium-ide/assets/18035861/b6920648-531b-4c91-9065-7c2370d37ff5)

I tried sending a simple "click" command, and I receive the same : a blank commented line, like if SIDE do not recognize the payload that I am sending him.
However, the payload I send is the one describe in the documentation.

Is this a known issue ?

Thanks

**Comment by toddtarsi** [comment]
There you are! I saw your message from IRC and responded after an hour, but I think I was bit too late. Reposting!

@vbaulac - I basically do this any time a site I’m working with uses content editables. This is a snippet from how I replace ‘edit content’ with a custom ‘writeToDraftJS’ command.

```
    const writeSucceeded = await browser.runtime.sendMessage(seleniumIDEExtension, {
      uri: "/record/command",
      verb: "post",
      payload: {
        command: "writeToDraftJS",
        target: 'css=.asdf',
        value: 'asdf',
      },
    });
 ```

Also, there’s a channel on slack ‘selenium_ide’. It's not IRC, but slack, so no Matrix integration and things tend to last forever there. Feel free to reach out there or here as both are persisted so I can get to em before/after work

**Comment by vbaulac** [comment]
Yay ! Thank you very much for your input, it works now !

The documentation is wrong/deprecated for the payload : https://www.selenium.dev/selenium-ide/docs/en/api/plugins/record

This is why I was in trouble sending the correct data. I don't know if I can warn someone to update it ? Or do it myself ;)

Thanks !

**Comment by toddtarsi** [comment]
@vbaulac - Honestly, I don't know how much longer v3 will work with the manifest changes (as far as I know, they're completely incompatible with commands like assert and execute-script). v4 is in version .45 here and is getting pretty stable:

https://github.com/SeleniumHQ/selenium-ide/releases/tag/4.0.0-alpha.45

Remaining items are adding a few more plugin capabilities around custom menu entries, using the example side files to test the ide and not just the side-runner, and adding a doc site or a github wiki or something. 

That said, I think you'll have a much better experience writing plugins for this than the web extension model. Focusing on just plugins, there are the following advantages:

1. It's typed.
2. Plugins support anything that NodeJS require() can find basically, so writing and sharing plugins just requires publishing an npm package instead of a webextension.
3. It supports project level plugins, so you can bundle side files and plugins in a single git repo.

There's a litany of other big pickups too, but those aren't relevant here.

**Comment by toddtarsi** [comment]
Oh, for point 2, you can also just have a js file for your plugin and the path to it from your project. Npm isn't required either. It's just meant to be a pain free way to open source stuff for other people.

**Comment by toddtarsi** [comment]
Also, that said, I'd give it one or two more weeks before you write any plugins for it. I'm basically adding those addl capabilities this week, so after this weekend, the @seleniumhq/side-api package is meant to be the one stop shop for all of your plugin writing needs. And then the next weekend, I'll start breaking ground on a github wiki or something so you've got some companion docs.

**Comment by vbaulac** [comment]
Ok thanks for infos ! I did not realize there was a big change incoming.
So far I am just building a POC of a solution for our testing issues. 
So the final solution will be in v4, with all the advantages of it ;)

Looking forward for your wiki !

**Comment by toddtarsi** [comment]
@vbaulac - Closing this issue. Please open any more for anything you encounter. Thanks!
