### ISSUE TITLE
Release date for the side-runner v4

### ISSUE THREAD

**Issue by fmrahman** [SeleniumHQ/selenium-ide#1743]
Hi @toddtarsi 

When are you planning to release the final version of side-runner v4? Eagerly waiting for the v4.

Thanks and Regards,
fmrahman

**Comment by toddtarsi** [comment]
@fmrahman - It's pretty much iterative. It's out already on npm. I think I'm up to like `4.0.0-alpha.61` there. Feel free to try it! If you need to migrate your side files from v3 to v4, you can just use a command like this I believe:

```
npx @seleniuhq/side-migrate ./existing_file.side ./new_v4_file.side
```
I'm not intending to make many changes to the side-runner. The main things keeping me from going to like a beta or stable release right now are just wanting a few more end to end tests of the IDE itself. The side-runner actually has great CI coverage.

**Comment by fmrahman** [comment]
Thanks @toddtarsi  for the update.
Would like to know what are the differences between v3 .side and v4 .side. 
Are any new commands introduced in v4?
Can you share a document that has a list of new commands or modifications introduced in v4.

Thanks,
fmrahman.

**Comment by toddtarsi** [comment]
@fmrahman - Any selenium IDE specific / non webdriver commands are deprecated. v4 is primarily an IDE change to use electron and webdriver for local playback. This way we don't have have two playback versions: Emulated JS for local playback, and then actual webdriver protocol for CI. This led to a whole class of errors where the two environments diverged, and also led to a bunch of weird-pseudo commands in v3, like webdriver close prompt on next command vs close prompt or whatever. Commands like that are gone and replaced by just close prompt, since both local and remote playback use the same core runtime. Further, I think there were a couple xpath specific commands that got changed to use all selectors. In those cases, the migration script should take care of all of that. There are some other things that changed in how plugins are referenced as well. These got simplified to except local relative and absolute filepaths, as well as node style require syntax.

**Comment by toddtarsi** [comment]
@fmrahman - We just added about 300 tests for the side-runner and side-runtime (underlying runtime) to the CI. Things here are getting very stable if you're worried about code drift or stability.

**Comment by fmrahman** [comment]
Hi @toddtarsi 
Thanks much for adding the new tests and preparing the code for the final v4 release.

**Comment by fmrahman** [comment]
Hi @toddtarsi 

I hope this message finds you well. We have been using selenium-side-runner v3 in the production for the past 3 years. We are very much grateful to the selenium team for that.

But now the selenium v3 has become old and some of its dependent node modules have CVE issues, our organization is forcing us to update selenium to a newer version. We will not get approvals to use selenium v4 in production as it's under the alpha version. 

Requesting you to please release the new selenium final v4 at the earliest. I know you have many challenges and bugs pending for the final release. Again, thanks much for your contribution

Thanks and regards,
fmrahman.

**Comment by toddtarsi** [comment]
@fmrahman - Deal. This weekend, I'll cut v4 out of alpha for all packages except the IDE itself. I will also move the IDE itself into beta. Thank you for your patience with everything. I look forward to seeing you on v4!

**Comment by fmrahman** [comment]
Thanks very much, @toddtarsi.
Appreciate your kind response to my ask.

**Comment by fmrahman** [comment]
@toddtarsi Thanks very much for releasing the selenium-side-runner v4.

**Comment by toddtarsi** [comment]
@fmrahman - Np! You should also be getting better error stacks back now too (we actually append the failing step to the error now)
