### ISSUE TITLE
How to generate chrome  extension

### ISSUE THREAD

**Issue by linavaos** [SeleniumHQ/selenium-ide#1841]
I need to carry out secondary development of Selenium ide based on browser extension. But I saw that the current project is an Electron. How should I do it.

**Comment by toddtarsi** [comment]
Hm. I'm not sure what to tell you here. I maintain the Electron one, and it's the latest version, and the only version I'm really supporting now, so I'd recommend it. Also, it has polling built into a lot of the commands, so I find it sorta just gets more stable. I think it's a better long term direction, but the extension is there and you can use it as long as webextension manifest v2 works.

**Comment by toddtarsi** [comment]
@linavaos - I'm going to close this for now. If you need to, fork the 'v3' branch of selenium-ide and maintain it to your hearts content. I'd love the help. However, watch out because webextension manifest 3 is coming, and basically forbids selenium ide from working normally, so you'll have to do some dumb stuff that might get you pulled from the store anyway.
