### ISSUE TITLE
The page keeping the extension port is moved into back/forward cache, so the message channel is closed.

### ISSUE THREAD

**Issue by e2info-tsujii** [SeleniumHQ/selenium-ide#1873]
## 🐛 Bug Report

Since last week, when I try to run a SeleniumIDE file that I was previously able to use, I get the error message
**"The page keeping the extension port is moved into back/forward cache, so the message channel is closed."**
and I can't proceed. 

![スクリーンショット 2024-11-22 160547](https://github.com/user-attachments/assets/d85e5dc7-07d7-4db8-b56e-f2f252a5ab6d)

In the past, this could be addressed by disabling the flag chrome://flags/#back-forward-cache, but it seems that this flag has disappeared recently.
I'd like to know how to solve this.

## To Reproduce

I don't know how to reproduce it exactly, but I was able to reproduce a test similar to the automated test we use and make it fail. However, for some reason the reproducibility is unstable and the error does not occur 100% of the time. If you rerun it several times, the above error will occur occasionally. Please see the sample file below.

## Expected behavior

I hope that the error "The page keeping the extension port has been moved into back/forward cache, so the message channel is closed." will no longer occur.

## Project file reproducing this issue (highly encouraged)
I created a sample error test on the sample site for automated testing.

[bccache_error_sample.zip](https://github.com/user-attachments/files/17867356/bccache_error_sample.zip)

When I run the "ErrorTest" in test suites in this .side file, I get the following error occasionally:

![スクリーンショット 2024-11-22 173840](https://github.com/user-attachments/assets/d933a01b-d7b8-4aa5-af96-0aad444709a6)

![スクリーンショット 2024-11-22 173944](https://github.com/user-attachments/assets/188888d0-235a-4b80-abc6-1f07be3b9539)

As mentioned above, the reproducibility is not 100%. It sometimes occurs when you rerun it several times. The points where it occurs also vary.

## Environment

OS: Windows 11 version 24H2 (OS build 26100.2314)
Selenium IDE Version:  version 3.17.2
Selenium SIDE Runner Version:  unknown
Node version: unknown
Browser: Windows Chrome
Browser Version: version 131.0.6778.86 (Official Build) (64 bit)

**Comment by 98gmarquee** [comment]
I had the same issue constantly with one of our applications at work. I had to go into the flags in chrome and flip the switch for bfcache then it would work.

Now, since chrome dropped access to that flag, the flag from command line still works, so I can still use this for a while yet.

I know v3 IDE (the last browser extension version that worked in chrome/edge/firefox) wasn't the most useful for many, but it served the purpose for me at my company until this happened.

To enable the flag, I created a chrome shortcut on my desktop, then put this in the shortcut target:
`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-features=DisconnectExtensionMessagePortWhenPageEntersBFCache`

**Comment by e2info-tsujii** [comment]
I added the option you mentioned in the comments to my Chrome shortcut and was able to successfully run SeleniumIDE. Thank you!
![スクリーンショット 2024-11-25 094324](https://github.com/user-attachments/assets/3f1a92bd-e20c-4973-9f54-1f874c703054)

In the future, we will also consider introducing SeleniumIDE version 4.x
