### ISSUE TITLE
Issue with running selenium-side-runner

### ISSUE THREAD

**Issue by macalimlim** [SeleniumHQ/selenium-ide#193]
I tried using the selenium-side-runner with a project I made with the Selenium IDE in Chromium. There is an error that it says that the project is an older format, I should reopen and save it again using the IDE. But when I run it again with the runner same error is still happening. I'm not sure if this is an issue with the runner itself or the IDE. Please advise, Thanks :)

**Comment by corevo** [comment]
Are you using the latest [beta](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v3.1.0-beta.5)?

**Comment by macalimlim** [comment]
beta of selenium side runner? no Im not using the beta version. I installed it thru npm. Should I use the beta version instead?

**Comment by corevo** [comment]
Can you post the script you're trying to run?

**Comment by macalimlim** [comment]
What I did was create a project using the IDE and then created some tests, linked those tests to a test suite, save it then ran it in the terminal like this..

$ selenium-side-runner MyTests.side

**Comment by macalimlim** [comment]
![selenium-side-runner-error](https://user-images.githubusercontent.com/5382992/39917888-7a6f6f80-5541-11e8-96c4-e873e404ba27.png)

**Comment by corevo** [comment]
The issue originates from the line
```js
jest.setTimeout(NaN);
```
Since the tests are async, and the timeout is `null` essentially, the test doesn't wait for the results, and kills the session immediately.  
My intuition is that you're using two different beta versions of the IDE and the runner.  
To fix it manually, you can go to the suite view in the IDE, and you'll see settings in the context menu, in there you can put the timeout in seconds, which should be `300` by default, but since I believe your IDE is of older version, it doesn't support it.  
In any case, confirm the IDE version.

**Comment by macalimlim** [comment]
Thanks, I got it working by specifying a timeout :+1:

**Comment by corevo** [comment]
I made sure to fix the timeout
