### ISSUE TITLE
Can selenium ide add support to export script to html format?

### ISSUE THREAD

**Issue by leoforever** [SeleniumHQ/selenium-ide#222]
The old selenium IDE can export script to html format, can the new IED add support for this?

**Comment by Jongkeun** [comment]
@leoforever ,
you can add the script  by clicking the folder shape button at the right over.

**Comment by leoforever** [comment]
I mean to save the script as html format, currently I can only save it to .side format

**Comment by Jongkeun** [comment]
I misunderstood.
As far as I know, you can't now.
We tried to load [old test](https://github.com/SeleniumHQ/selenium-ide/issues/95) case perfectly, but not talking about it.

**Comment by leoforever** [comment]
Will it be supported in future?

**Comment by corevo** [comment]
If you're wondering about exporting to languages, have a look at #131.  
html is not an "export" per se, it is the save format, and the new save format is side because of the restrictions posed by browser vendors on our abilities to load files.  
Unless access to the filesystem will be changed by browser vendors, this is the format going forward.

**Comment by 98gmarquee** [comment]
Sorry for my ignorance, but is "side" a format/language of some type? Looking at it, it's obviously not as simple to read/write/edit/copy as the old html ide scripts were.

**Comment by corevo** [comment]
I have given my thoughts about that [here](https://github.com/SeleniumHQ/selenium-ide/issues/150#issuecomment-381394857).  
I'm starting to think that perhaps switching the format underneath may be a good idea.

**Comment by solidevolution** [comment]
Important for me is, that you shouldn't build own formats (only for internal open/save)

Selenium V1 (HTML) looks like a given "standard"
Selenium V2 (JSON with XML (wtf!?) looks like an alpha

Currently I know a lot of modern E2E languages (programmatic) but all IDE's i found looks old and broken.

Selenium self is used in many cloud solutions and test frameworks. That's why programmatic way is trendy currently.

To get more professional tools, some one with more experience should define an real import/export format for selenium test with all features (wait etc.) in an human readable format.

**Comment by sergueik** [comment]
@Tomer is this closed discussion ?  

I has a promising tool one can use existing code already to deserialize the custom json|side ? 
i has a swt and  javafx ui avaiailable:

https://github.com/sergueik/SWET 
https://github.com/sergueik/selenium_java/tree/master/swet_javafx

uses jtwig for code gen

**Comment by dvgrn** [comment]
So far the most helpful link I've found for this problem is the following online converter:
  http://output.jsbin.com/zagemaw
Paste the text from a 3.x SIDE file into the top text box, click Import, then Export, and copy the resulting HTML out of the bottom text box.
