### ISSUE TITLE
[Question] Any reason add onFocus to TestRow?

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#232]
@corevo 
You added `onFoucus` at 7a7aea49620b94255d5cb4e4e0b2cbcd4727574e.
Even if I removed this handler, it worked well.

Was there specific reason about adding `onFocus`?

**Comment by corevo** [comment]
Yes, when you navigate with tab it'll focus the element, I wanted that behavior to select it as well.

Cheers,
Tom

**Comment by Jongkeun** [comment]
After you arrive at the office, would you tell me the difference about the case which `onFocus` is and the case which `onFocus`  is not? I don't know about it. 
I started to make the commands multI-selection possible.
But `onFocus` makes a problem by calling `select` function twice.
So If it is possible to remove this handler, I thought it made this task more easily.

**Comment by Jongkeun** [comment]
I wanted to solve the problem before I saw #189.
First, I thought I should change `this.selectedCommand` on `UiState`.
But, it has many point to break side-effect.
So I changed the concept.
Leave `this.selectedCommand` and add a new variable as array.
And replace the `this.clipboard` to array.

I made util multi-copy and paste after removing `onFocus`.
But if `onFocus` is necessary, I will try to other way.

**Comment by corevo** [comment]
I understand, `onFocus` will make the command selected so that if you `tab` into it from a different place, it will correctly select it to enable the arrow and other events that should be set.  
If you're adding an array of selected command in addition to the selected one, which sounds a very solid idea in my opinion, the `onFocus` should remain unchanged, since it only affects the `selectedCommand` rather than the array (unless that command does not appear in it, in which case you should add it).

**Comment by Jongkeun** [comment]
OK, I will add duplication check logic and leave `onFocus` unchanged.
Thanks.
