### ISSUE TITLE
Where are Selenium IDE's functional tests?

### ISSUE THREAD

**Issue by yozlet** [SeleniumHQ/selenium-ide#248]
After hitting a couple of strange bugs in Selenium IDE, I decided to take a look at the codebase and see if I could fix them myself.
But I've been looking around for tests to run on the IDE itself and I've found nothing. There is a handful of tests for the runner, storage and a couple of the models, but I can't find any functional tests of the UI, nor any unit or integration tests for most of the components.

Am I looking in the wrong place? Or does this functional testing tool really have no functional tests?

**Comment by corevo** [comment]
I want to say we have good coverage but I'm afraid that it's not the case atm.  
Mostly because testing WebExtensions isn't very important to the industry, no major vendor has provided a mock for WebExtensions, there is an ongoing [oss intiative](https://github.com/clarkbw/jest-webextension-mock), but since Selenium IDE, more than most WebExtensions coupled with many different browser features to perform automation on every aspect, there is no mock that can suffice.  
Meaning there is no test environment that can load the UI code, so we test what we can, WebDriver, which is the driving reason behind #230, this way I can test the automation aspects using WebDriver, and depend less on WebExtensions which will allow me in turn to test the UI.  
FYI this is how [Mozilla](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension#Testing) recommends to test extension, the situation is pretty dire for the WebExtension ecosystem, and I'd really welcome any help I can get on this.  
If you can give a hand in decoupling Selenium IDE from WebExtension, and move it towards WebDriver, and other well established platforms, then I'd love that.

**Comment by corevo** [comment]
Closing, OP can answer to reopen.
