### ISSUE TITLE
Issues when migrating from the old version(2.9.1) to the new version(3.1.0)

### ISSUE THREAD

**Issue by joselitoeu** [SeleniumHQ/selenium-ide#258]
OS:  Windows 10/Windows Server 2012
Selenium IDE Version:  3.1.0
Browser:  Firefox
Browser Version:  60.0.2 (64-bit)

I currently use the 2.9.1 version, while trying to use the new version i found a few issues that make it unusable to me:

-Lack of scheduler, we use the scheduler to run the tests suits everyday.

-No plugins, we use a file logging plugin to generate a log file of the execution, it would be nice if the new version had a native file log generator.

-Lack of support for the scripts wrote in the old version, some crucial commands like "waitForX"(waitForVisible and waitForNotVisible are the most used) is not in the new version, we have over 400 scripts, some with more than 5k lines, using "pause" is not an option.

-Every test case in the new version is generated in 1 single file in json format, this is bad for CVS control, in the old version every test case has it's own file, easy to manage and control via CVS.

OBS: Sorry if i missed something, I'm new to github.

**Comment by cgoldberg** [comment]
from the current README:

> "This project is a work in progress
> [snip]
> As this is an early stage and many things aren't clear, it's quite challenging to collaborate and coordinate the efforts - so please be patient."

**Comment by corevo** [comment]
Hey just wanted to chime in, as @cgoldberg said, it is a fairly early stage of the project, and we are reluctant to take big feature requests, usually the ones we take are just things we already have in our roadmap.  

First off, opening multiple issues in one ticket makes it hard for maintainers to follow up with it, without reading everything each time, the title should let maintainers know exactly what’s the issue. For next time open multiple smaller issues, it keeps the conversation specific to a problem.

To your points:  
Scheduler isn’t coming, we are working on a CLI runner, you can setup a [cron job](https://help.ubuntu.com/community/CronHowto) to run it. Other operating systems have other alternatives, such as Task Scheduler for Windows or launchd for macOS.

We have [plugin system](https://github.com/SeleniumHQ/selenium-ide/wiki/Getting-Started-with-Plugins), but WebExtensions don’t let us write files in the system (it is a browser limitation on extensions nowadays), so the best you can do at this time is to indeed copy-paste the log, perhaps it is worth having a button to download the log (e.g. save as).
If you want to write logs to the system, when the runner is live just run `selenium-side-runner project.side > log.txt`.

It’s not lack of support, `wait` commands are obsolete, for most cases the implicit wait should be enough, for other cases you are more than welcome to write a [plugin for it](https://github.com/SeleniumHQ/selenium-ide/wiki/Adding-a-Command).  
At the moment, we are trying to move to a more user defined scripts, rather than browser defined, removing `wait` commands is a step towards that, but you can write a plugin that reimplements them.

The new format is designed to give better suite management, and better control over CLI running, which outweighs of splitting the files, this is the format going forward.

**Comment by corevo** [comment]
@joselitoeu if you don't mind me asking, what is your use-case for `waitForNotVisible`?

**Comment by joselitoeu** [comment]
@corevo Thanks for the more elaborate response. Some parts of the system has a transition "popUp", like a small loading screen, that only closes when the systems process all the data(transmitting or receiving), so sometimes the page in the background is fully loaded but the system is still processing something internally, and the function of this "popUp" is to block any interaction with the screen bellow until everything is processed. Basically we use the "waitForNotVisible" to wait for that "popUp" to close.

About the scheduler, I'm not familiar with CLI runner, how can i use the Windows task manager to run the Selenium IDE? I tried to search around and didn't found how to do it. I know i can use a batch to open the Firefox, but i don't see how i would run a plugin inside it.

**Comment by corevo** [comment]
You're not opening the plugin, you're not running the plugin at all.  
It's a CLI tool that can run project files without the need to the extension.  
It's in [beta](https://www.npmjs.com/package/selenium-side-runner), and you'll need a beta version of the extension as well.  

About the `wait`, indeed our implicit wait can't account for a use case like yours, I'm gonna consult with other team members to see what they think about this, and we'll come up with a solution to this problem, I'll open a new ticket with our findings, I'll make sure to tag you.

**Comment by joselitoeu** [comment]
Interesting, i will check the CLI runner, thanks for the answers.
