### ISSUE TITLE
Make var's available for entire Testsuite

### ISSUE THREAD

**Issue by el-andaluz** [SeleniumHQ/selenium-ide#335]
## 🚀 Feature Proposal

When a variable is stored during a test, it should be available until the testsuite has finished.

## Motivation

Worked on SeIDE v2.x .

## Example

I have some tests where I have to sign in to a portal and fill out some contact forms.
For this I normally used a test who runs before all others, to calculate and prepare those variables. When testing the Webapp, I can get common values from the stored var's.

**Comment by corevo** [comment]
It is not the intended behavior, this will result in tests being non-idempotent and non-isolated.  
For that reason we have under options the ability to persist the session, which will do that amongst other things, it will also link you to an article written by Google on why this is a bad practice.  
![image](https://user-images.githubusercontent.com/888886/44029602-8bb59f12-9f06-11e8-89cd-85977118456c.png)
I would recommend finding a way around this, if possible, if not, you could certainly settle for that option.  
Also as a side note, we are moving away from bad practices the old IDE has imposed, saying:
> Worked on SeIDE v2.x.  

Is not a good reasoning for a feature, it does not mean we won't forward port more features, but any feature from the old IDE, will require you to specify a reason for it's existence other than, it used to exist.

**Comment by corevo** [comment]
Cheers!

**Comment by 98gmarquee** [comment]
I did this all the time as well. It kept me from having to put values into 50 test cases. I'd have one test at the start that stored all the variables that were "static" for the current iteration, then use those variables in all 20 tests.

Things such as storing a js timestamp for "now", storing the server I need to test on, the userid I wanted to use for testing internal web sites. For the timestamp storage, I'd store "now" to the second for keying record names in each script. Each script would then have a suffix in the name unique to the script, but all having the same prefix timestamp made it quick/easy to find the records, but also made them unique so as not to get caught by duplicate checking we have in our sites.

When I first started using Selenium IDE, I'd have those values in each test case, then do global updates within a folder using notepad++. This was fine when working in the office as the files/folders were on the network. When working remotely, it adds a lot of time due to the VPN not being nearly as fast. So, is started using a single script to store the values instead and found that to be more convenient.

**Comment by 98gmarquee** [comment]
Is there harm in retaining the variables within a single test?

I have scripts where I store record id's generated by the system to use later in the scripts for lookup purposes. If the script fails somewhere along the line and I stop it, make a change, then use "play from here", it loses the variables stored from the previous steps.
