### ISSUE TITLE
Where is the Focus command?

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#351]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

1. Is there any reason why there is not `focus` command?
2. Do you have any plan to make alternative commands of `not` commands?
  (`waitForNotVisible`, `waitForWindowNotPresent` etc..)

**Comment by corevo** [comment]
Maybe a feature request template is better for this, getting to the point though:  
 - There will be `focus` command, but atm we can't properly focus elements, because we can't control the input devices (mouse & keyboard), I think it will create more confusion than help.
Once we move to playback on WebDriver, we will definitely add that.
- Currently the only 2 wait commands that I can think of that we have actually deprecated are: `waitForElementPresent` and `waitForPageLoad`, other wait commands are definitely possible to add.
Especially ones that can't be assumed implicitly like `waitForNotVisible`.

**Comment by Jongkeun** [comment]
@corevo But we filtered `wait` commands in `migrateTestCase`.
It is not a problem if someone defines a command in new Selenium-ide, but if someone imports old script which has `waitForNotVisble`, it breaks out a problem. 
Please consider this part as well.

**Comment by corevo** [comment]
You're right on this, we should take a look at the whole list of `wait` commands and decide one by one, which ones are supported, implement them, and only then **exclude** them from the migration process.
