### ISSUE TITLE
Selenium-side-runner Tests cannot be run without Testsuite

### ISSUE THREAD

**Issue by M3ssman** [SeleniumHQ/selenium-ide#352]
## 🐛 Bug Report

If the Default Testsuite is deleted for whatever Reason and there is no other Suite present, the *.side -File cannot be run headless, in opposite to Chromium, where this is still possible.

Consider a *.side File like

```
{
  "id": "420d12ae-26c0-4765-a53c-f31b60d89964",
  "name": "Untitled Project",
  "url": "",
  "tests": [{
    "id": "c0405784-8101-407a-ba65-dec2836a1bbe",
    "name": "test-bug-testsuite",
    "commands": [{
      "id": "07d666c6-6d45-4f08-bd04-118213deff3a",
      "comment": "",
      "command": "open",
      "target": "http://de.wikipedia.org",
      "targets": [],
      "value": ""
    }]
  }],
  "suites": [],
  "urls": [],
  "plugins": [],
  "version": "1.0"
}
```

Outcome:
```
error:   Cannot read property 'forEach' of undefined
```

## To Reproduce

Create a *.side File named `bugreport-testsuite.side` with contents above an run `./node_modules/.bin/selenium-side-runner  bugreport-testsuite.side `

## Expected behavior

Alike in the Browser, the Side-Runner should work with Testcase alone.  
At least, a more precise Error-Message is expectable.

## Environment

OS: Ubuntu 16.04 LTS
Selenium IDE 3.2.2
Selenium SIDE Runner 3.2.0
Node v8.11.2
Browser: Chromium Version 68.0.3440.106 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by corevo** [comment]
A better error message is expected.  
There are suite level settings that the runner requires in order to operate, maybe I can try to assume them, and assume you want to run all the tests?  
Because suite determines the test environment (timeouts, variable handling etc...), as well as act as a way to filter tests (e.g. `--filter` flag works on suite names rather than tests).  
For the time being I'll add a message saying that you should put your tests in a suite.  

As an enhancement, we can add the `--test-match` flag, to filter tests by name, and create a default suite if there are none.

**Comment by corevo** [comment]
Added a useful message on 0bd1202f9c11a8b088e08e1bc051c59cc86d23a6.  
Keeping this open for the feature request part.

**Comment by toddtarsi** [comment]
A bit less finicky in v4. No matching suite means we just run all tests in project.
