### ISSUE TITLE
"mouse over" does not work

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#362]
Run the attached scenario:
[mouse_over.zip](https://github.com/SeleniumHQ/selenium-ide/files/2313705/mouse_over.zip)

"mouse over" command is green, but it does not provide any effect:
![image](https://user-images.githubusercontent.com/617090/44515941-71f1a080-a6cc-11e8-9e2d-0016e2df3f27.png)

## Environment

OS: Windows 7
Selenium IDE Version: 3.2.4
Browser:
Browser Version: Firefox 61

**Comment by corevo** [comment]
This is a known weakness in the IDE that can't be resolved for Firefox.  
The reason is, that through WebExtensions we can't control the mouse movement, only emit [untrusted events](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) of mouse move and the likes.  
Since JavaScript generated events do not control wether or not the browser should apply the `:hover` pseudo class to an element, we can't simulate it.  
In order to overcome this for part of the user base, I've pushed a fix that uses [CDP's dispatchMouseEvent](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchMouseEvent) to accomplish this (080fd93a83016d41a5763c27298f97377cf02d9a).  
If hover as in (`:hover` pseudo class), is necessary for the scenario, I would recommend using the Chrome version of the extension.  
The same is true for 2 other cases where we relegated to a fix through CDP, which is for `KEY_ENTER` to submit a form (through the browser's default behavior), and to upload files, since `input.files` is read-only, and we have no filesystem access.

**Comment by corevo** [comment]
A way to circumvent this, is to allow extensions to access marionette, but AFAIK Mozilla have no plans on doing that.

**Comment by whimboo** [comment]
Note that if all is self-contained you may be able to get those features by implementing such APIs via
https://webextensions-experiments.readthedocs.io/en/latest/

**Comment by barancev** [comment]
Is it true for `:hover` only?

I have another example, top menu on http://litecart.stqa.ru/ , I'm trying to click a submenu item:
![image](https://user-images.githubusercontent.com/617090/45093748-0d016600-b122-11e8-9ebe-d6198b840428.png)

**Comment by corevo** [comment]
@barancev yes, the submenu is visible via `#site-menu ul li:hover > ul`

**Comment by sergiybuch** [comment]
I have the same issue in Chrome extension. Mouse over is not working.
