### ISSUE TITLE
Let's separate "save" and "save as" actions

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#363]
## 🚀 Feature Proposal

Let's suppose a user opened a project from a file, edited it and attempts to save it. In this case Selenium IDE should not ask for a file name, it should save the project to the same file.

Let's suppose a user created a new project and attempts to save it. In this case Selenium IDE should ask for a file name.

Let's suppose a user opened a project from a file and wants to save a copy of this project to a different file. Selenium IDE should have an action separate from "save", let's call it "save as", to provide an ability.

**Comment by corevo** [comment]
I think I've answered this issue before, I can't exactly say where (there's been multiple issues about this), but it is a known issue which we have no way around.  
The IDE is a web-app, and as such the only way to save a file to the system is to download it, web-apps have no write/read access, we perform open by using `input[type=file]`, and save by downloading.  
When loading a file, we can't tell from which directory it was uploaded, only it's name, which further complicates this issue.  

Another implication of this is file uploads, since we can't read files, we can't upload, we work around that by strapping into [Chrome's DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/tot), which is unavailable in Firefox.  
The last implication of web-app architecture, is the inability to spawn processes, meaning when we use the WebDriver bindings, we must connect to a standalone Selenium server to operate, because we can't spawn a driver process.  

I hope that clears it, mostly we don't have access to process and filesystem (only indirect though file inputs and download).  
Which is why I'm in favor of moving to electron in a future version.
\cc @tourdedave @shs96c

**Comment by 98gmarquee** [comment]
@corevo not to make it blatantly obvious I don't know the things you guys do, but "electron" vs what?

**Comment by corevo** [comment]
electron vs webextension

**Comment by luquitia** [comment]
OK about the file structure, but can we at least remember the file name that was actually opened?   See issue #441 which includes that issue (along with the save as / file structure issue).

**Comment by mirao** [comment]
Very annoying issue. If not automatic "save" after `Ctrl + S`, then at least path to my project should be remembered. Now I have to change folder anytime I press `Ctrl + S`. Folder` ~/Downloads` is offered instead of expected `~/selenium-ide` where the project is stored.
I'm running Ubuntu 18.10

**Comment by corevo** [comment]
Now that we are working on moving to electron, autosaves, and save in place are possible.  
This will be available in our WIP electron version of the IDE.

**Comment by darkartswizard** [comment]
This is awesome!

**Comment by MiiChiel2000** [comment]
I saw in a different topic that saving the project with a the chrome plugin does not work well. The extension reads .txt instead of .side (https://github.com/SeleniumHQ/selenium-ide/issues/861)

Yet now 10-01-2020 i downloaded the latest plugin for Chrome with chrome version 79.0.3945.88. But the projects are saved without extension. For instance: e6112f02-93ab-4909-92c9-266164cedace

adding .side with it and they work while opening.

**Comment by corevo** [comment]
It is worth to keep track of [showOpenFilePicker](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker), still not implemented in Firefox, and the [spec](https://wicg.github.io/file-system-access/#api-showopenfilepicker) only requires availability in https, the spec specifies that availability in [extension context](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy) is up to the vendor.

**Comment by toddtarsi** [comment]
This is completed in Selenium IDE v4.
