### ISSUE TITLE
Jquery is not defined in Google Chrome

### ISSUE THREAD

**Issue by tom-orrow** [SeleniumHQ/selenium-ide#368]
Trying to run simple execute script "$( document )".
It works in firefox extension and shows "$ is not defined" in chrome. Same result for "!!window.jQuery", even though I can use jQuery in browser console.

Selenium IDE 3.2.0
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Firefox 61.0.1 (64-bit)

**Comment by corevo** [comment]
It is an issue with Chrome I suggest you open an issue with them.  
Chrome only offers [eval](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Using_eval()_in_content_scripts), while Firefox provides the correct `window.eval`.  
Open an issue with Chrome about this.  
Also follow the issue template next time, otherwise the issue will be closed.

**Comment by Verron** [comment]
@corevo I'm not sure I follow your eval explanation for chrome completely. Does chrome extensions not have access to loaded scripts when using eval? I ask because this line fires as desired.

```eval("$('.ag-cell-last-left-pinned > span span').first()[0].dispatchEvent(new MouseEvent('contextmenu', {bubbles: true}))")```
