### ISSUE TITLE
Adding ability to check if last command pass/failed

### ISSUE THREAD

**Issue by modnar1226** [SeleniumHQ/selenium-ide#369]
## 🚀 Feature Proposal

A clear and concise description of what the feature is.
2 Parts.
Part 1: Toggle the automatic stoppage of the runner using a global variable either as a command or a UI feature.
Part 2:  When stoppage is turned off, ability to check status of a previous command using a js statement.

## Motivation

Please outline the motivation for the proposal.

It would open up avenues for testing if some object failed to load, do this instead, or adding logic for test cases to handle problematic areas.

## Example

Please provide an example for how this feature would be used.

Scenario: runner clicks a link, its buggy so it opens 2 windows. The test also opens other windows later in the test causing pre-programmed logic to fail due to window numbers being off count.

Example: being able to test if the last command failed and being able to try another window number.
command: if
target: ${!lastCommandOK}
value: Try something else.

**Comment by twnew** [comment]
> target: ${!lastCommandOK}

Since the variable names are the same, I guess this is essentially the same feature/idea that Kantu has or? 

See here: [${!lastCommandOK}](https://a9t9.com/kantu/docs#!lastcommandok)

**Comment by modnar1226** [comment]
Yes the idea comes from Kantu, although the variable could be called anything.

**Comment by corevo** [comment]
If a command fails then the test throws and quits.  
It seemed to me that the correct feature proposal would be to add `try` and `catch` commands to the control flow.  
This type of "magic" variable goes against the paradigm that control flow is trying to push.  
I am not familiar with any composable and scalable control flow structure, that instead of `throw-try-catch`, gives you a way to check if the last command was successful (other than [runtime.lastError](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/lastError), and we don't even use that).

**Comment by M3ssman** [comment]
Anybody can clear the Relation between Selenium IDE and Kantu? 
Thought the later one has been forked from Selenium?

**Comment by twnew** [comment]
> This type of "magic" variable goes against the paradigm that control flow is trying to push.

Totally agree  - but it works ;)

>Anybody can clear the Relation between Selenium IDE and Kantu?
>Thought the later one has been forked from Selenium?

Kantu was actually the first new Selenium IDE. I used it already last September ;-) They started at a time when there was no official Selenium IDE TNG project yet. So the [code base](https://github.com/A9T9/Kantu) is completely different, it's not a fork.

**Comment by tourdedave** [comment]
As Tomer suggested, this will be handled with `try` and `catch` commands in control flow. Closing this and will track the progress in #718.
