### ISSUE TITLE
element:contains() selector is no longer valid

### ISSUE THREAD

**Issue by wangchj** [SeleniumHQ/selenium-ide#373]
## 💥 Regression Report

Recently updated to Selenium 3.2.5. After the update, many of our tests are broken. The broken tests use `element:contains("text to check")` to check if the inner text of an HTML element contains certain text. An example is below:

```
command: verify element present
target:  css=#jsonModal pre:contains("propertyName")
```

This check is very important to us because we construct configuration JSON and we have a lot of tests performing this check.

We're aware of the `verify text` and `assert text` command. However, these appear to check the entire string, and do not take patterns.

## Last working version

Worked up to version: < 3.2.0

Stopped working in version: 3.2.4

## Expected behavior

Allow element:contains() in target selector to verify certain text exists.

## Environment

OS: MacOS Sierra
Selenium IDE Version:  3.2.5
Selenium SIDE Runner Version: ?
Node version: 10.1.0
Browser: Chrome
Browser Version: 68.0.3440.106 (Official Build) (64-bit)

**Comment by corevo** [comment]
I suggest you take a look at the [migration guide from Selenium RC to WebDriver](https://www.seleniumhq.org/docs/appendix_migrating_from_rc_to_webdriver.jsp#finding-by-xpath-or-css-selectors-doesn-t-always-work-but-it-does-in-selenium-1), the `:contains` pseudo class is a non-standard CSS capability that Selenium 1 provided.  
Selenium 1 is a-non supported 15 year old technology, that was deprecated a long time ago.  
With WebDriver (Selenium 2), only CSS selectors that comply with the W3C specification work, thus `:contains` no longer works.  
I suggest migrating tests to use different selectors, `xpath` can refer to the contained text of the element.  

This change had 2 reasons:
 - We are working on deprecating the current playback in favor of playback on WebDriver, supporting that is simply impossible.  
 - We've made this step in advance, because in the future (September 1st) Mozilla will stop supporting that code, meaning no updates can be made to the IDE codebase without us removing it.

The IDE will take incremental steps towards playback on WebDriver, which will render some capabilities obsolete, such as this one.

**Comment by wangchj** [comment]
Using xpath works. Thanks!
