### ISSUE TITLE
Is there a plan to support Keywords

### ISSUE THREAD

**Issue by youwi** [SeleniumHQ/selenium-ide#394]
## 🚀 Feature: Keywords
Is there a plan to support Keywords
just like  RobotFramework Keywords.

## Motivation

 to reuse Web Action
Without this feature Selenium-ide to be that  just a toy tool .

## Example

| keyword | my click|
| click  | @{arg}   |
| click | @{arg}    |
| do somthing     |

test case
| my click | 1 |
| my click | 2 |

**Comment by corevo** [comment]
Before adding more syntax to the IDE, we have to consider the complexity it adds with it, and how the users will learn it.  
We don't want to create a tool that is overly complex, that will deter people from using it's features.  
To that end, instead of proposing a solution, I would kindly ask you to explain what is the issue you are facing?  
Is it reusing a common sequence of commands? in that case we have the `run` command.  
If it's something else, post the problem you're facing, and we'll think of a solution.

**Comment by youwi** [comment]
100+ test cases.  3 user roles on my page. 
when HomePage(login page) changed ,that is a disaster.

**Comment by tourdedave** [comment]
Thanks for the feedback @youwi. The best option we have for your circumstance right now, which @corevo mentioned in an earlier comment, is the `run` command. With it you can use a test case inside of another test case. So, if you have a test case solely for login, you can reuse it in any test that needs to log in. The amount of overhead in transitioning to this command would be minimal since you would just need to swap out the keyword command you were using for the run command.

**Comment by youwi** [comment]
`run` command  is a good plan. but sometime that make dead loop.

**Comment by tourdedave** [comment]
I don't follow your example. Why wouldn't both login tests be autonomous? And what's the issue with the page reloading in `test other`? In order to log in you would need to visit another page. And if you need to use two different logins as part of a test, then this sounds like a necessary requirement.

Can you please elaborate on what you mean by "test case management is another disaster"? Speaking in hyperbole isn't helpful or actionable.

**Comment by tourdedave** [comment]
The use case you've outlined works with the `run` command. Make a test case you want to use as a keyword (e..g, `Login2`) and refer to it with the `run` command from another test. The session will automatically persist.

**Comment by youwi** [comment]
yeah. that works.
then ... maintaining cases is a "Large" job.

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
