### ISSUE TITLE
clickAt command should click once

### ISSUE THREAD

**Issue by barancev** [SeleniumHQ/selenium-ide#40]
See the scenario and the log:
![image](https://user-images.githubusercontent.com/617090/32727138-7dab1f60-c88c-11e7-9660-9f6ccaff8803.png)

**Comment by corevo** [comment]
It does click only once, but it retries the click until the element appears, or fails after 30 seconds due to timeout.  
Once it successfully clicks it logs success or failure and moves forward.  
I thought it was better to log the amount of retries, do you think I should log it once, or in a different manner?

**Comment by barancev** [comment]
In WebDriver, waits are tied to "find" operations. If you want to log attempts, it would be more natural to see something like
"trying to find..."
"trying to find..."
"trying to find..."
"clickAt"
in the log.

If you want to change this logic, it should be negotiated and approved by the dev team.

**Comment by corevo** [comment]
I'm wondering what's the best way to achieve this experience.  
Currently the extension tries to communicate the command to the tab under test, to which we have 3 results.
- The command was successfully executed
- The element was not found
- Other errors (tab was closed mid-test, etc)

Thus, by the time I know wether or not the element was found, if it was found, then the click already went through.  
I can say, trying to find instead of executing, and say that it was executed instead of simply success,  
But really, what the extension is trying to do, is to execute, and not simply find, which we do not communicate that way in the logs.  

Do you think that's a problem, or to change as I mentioned?

**Comment by corevo** [comment]
Since of reasons I mentioned above, how is this change?
<img width="601" alt="screen shot 2017-11-22 at 16 32 15" src="https://user-images.githubusercontent.com/888886/33132631-d096412e-cfa2-11e7-876e-69edfbdc4517.png">

**Comment by barancev** [comment]
There are more than three possible outcomes.
1) success
2) element not found,
3) element found, but operation failed, because element is not appropriate (e.g. an attempt to select from drop-down menu, but the found element is not 'select') or its state is not appropriate (e.g. it is invisible), or element is stale, removed from the DOM (yes, this can happen too)
4) other errors

In all cases except for 1) a user would like to see what happened.

It's important for debugging. If I see an element can be found -- it must be a wrong locator. If I see the element can't be clicked -- I know the locator is OK, but the element is not ready to interact with, and I have to add some waitings.

**Comment by corevo** [comment]
In addition to the previous comment, the extension will now log if it's waiting for the Element to appear, or if it has reached a timeout waiting for it to appear
