### ISSUE TITLE
Separate testCase and testSuite

### ISSUE THREAD

**Issue by rob1gr** [SeleniumHQ/selenium-ide#401]
## 🚀 Feature Proposal

In the old version we have 2 notion : 

- testCase (html file with the action of test)
- testSuite (html file with only link to different testCase)

Now we have testCase and Project (but i suppose they are dependent)

Is it possible to use one testCase in many testSuite ?

There's no button to import testCase existing.

## Motivation

Do not have to rewrite a test several times (example a connection window that is used in several projects)

## Example

Please provide an example for how this feature would be used.

**Comment by corevo** [comment]
Test cases and test suites are separated, a suite can contain multiple test cases, and some suite can share the same test cases, you the navigation menu to change the selection between them.

**Comment by rob1gr** [comment]
when we save there is only a file with .side extension. 

Before there is one file for one testCase and an other file for the testSuite 

How to use a testCase of this in an other testSuite ?

**Comment by corevo** [comment]
Now I understand your point, we have merged suites and tests into a project file `side`, this move had a few reasons behind it, most notably the fact that the new extension format is cracking down on what an extension can do on your computer (for good reasons).  
For example the old format, an extension can read files on your computer with no discretion, which means that if you open a test suite file, it can automatically open the test cases involved.  
In the new format however, extensions can only read files that you **explicitly opened, and none else**, which means that every time you wanted to open a suite, you would have to manually navigate to 20 different test cases and open them manually.  

In order to not do that, and have you only open one file, we needed to merge all the data into a single file, bottom line, the `side` format is not going away, and it is the way for the IDE moving forward.

**Comment by rob1gr** [comment]
So it is impossible to use a testCase present in a .side file in another project? Moreover how to integrate this into HUDSON which asks for a testSuite file (html format currently)?

**Comment by corevo** [comment]
Currently no, but it is a feature worth opening a ticket for, I guess the implementation would be to copy it over, which is less ideal.  
I don't know what HUDSON is, but I suggest opening a ticket for them to support the new format.

**Comment by rob1gr** [comment]
so i open two new tickets ?
