### ISSUE TITLE
Element not found... but it is

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#425]
## 🐛 Bug Report

Sometimes Selenium IDE says it could not find an element (Find target in page - magnifying class) but it highlights the element and the element's CSS selector is correct. Unfortunately I could not screenshot the element being highlighted but it flashes on and off for a second.

![image](https://user-images.githubusercontent.com/498834/46197255-8ba88800-c309-11e8-9bea-073270ae7031.png)

As you can see in the screenshot the element exists and is accessible via jQuery with `$('div.product-header-image > div > button')[0]`.

I suspect the element is out of view and we do see a possible JavaScript error in the extension each time we try to view the element `Uncaught TypeError: Cannot read property 'clientX' of undefined` in `assets\record.js`.

**Comment by jngale** [comment]
This may be related to issue 423.  I reproduce this regularly when the target is in an iFrame.

**Comment by luquitia** [comment]
Hey, I ran into an issue like this related to a recent code change on my test application.

My issue was a **verify not text** command that passed one day (last week) and started failing the next (after new build) saying it could not find element or timing out.  Then, when I changed the command to **verify element not present**, I get the opposite error, saying that element is found.

When I inspected the code (the HTML), I could see that my Xpath element was there in the code, but it was "hidden" (gray node text in Firefox Inspector console) as it was tied to a script node which hides the subsequent child nodes, including the node I wanted to test.  It was hidden previously also, but I guess the HTML changed in some way that made "verify not text" no longer able to find it. And/or it was a change due to Sel IDE 3.4.0 which came out same day I found it.

Since I was only trying to verify that an element/text was hidden here, I was able to work around this by using **wait for element not visible** command (as there doesn't seem to be any "verify not visible" type command in the new IDE).

_Note: in my case, the code was not in iframe, but regular HTML node controlled by script (html attribute type="hidden")._

**Comment by cawoodm** [comment]
We don't have any iFrames but I can reproduce this in certain circumstances. Again today:
Element is findable by jQuery:
![image](https://user-images.githubusercontent.com/498834/47420124-fec4e300-d77d-11e8-996f-fcbe613914cb.png)
The IDE says it can't find it:
![image](https://user-images.githubusercontent.com/498834/47420150-0c7a6880-d77e-11e8-8fc7-f81f7cbd22f3.png)
Even pressing 'X' to repeat the command: IDE can't find it.

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity, and a lack of a reproducible test case.
