### ISSUE TITLE
Is there a solution for generating C# test scripts?

### ISSUE THREAD

**Issue by Cyberjpb** [SeleniumHQ/selenium-ide#436]
Is there a solution for generating C# test scripts?
If not, when do you plan to make this feature available?

**Comment by corevo** [comment]
We know we do not have a code export solution atm, but we are not receiving tickets on the matter.  
All current conversation is taking place in #131.  
I would recommend you in the meantime to take a look at the [selenium-side-runner](https://www.npmjs.com/package/selenium-side-runner).  
Moreover since this is an open source project, and the time spent on the project is solely by contributors free time, we do not give timeframes on any issues.
