### ISSUE TITLE
this.playingFrameLocations[e] is undefined

### ISSUE THREAD

**Issue by apocalysque** [SeleniumHQ/selenium-ide#447]
## 🐛 Bug Report

Since upgrading to latest version (it was automatic, I didn't consciously choose to upgrade) the selenium IDE doesn't work for me at all in Chrome or Firefox.  In the previous version I was using, I was able to open Selenium IDE, record testing commands, and then repeat those commands individually using the recorded commands in Selenium IDE.  Now when I start the Selenium IDE it prompts me with some lame start up screen asking me if I want to create a new project or open an existing project (neither of which I want).  The only other option on that screen is to close the Selenium IDE (useless?).  Then, if I create a project like it insists, before it will allow me to record testing commands it insists that I enter a starting URL.  This URL opens in a new window (also something else I don't want, this is a dynamically generated page, I don't need to reproduce all the steps to get here, I only want to generate tests on this particular page).  Once I finish recording my commands and try to run a single command on the test if fails every time.  In Chrome it give me an error message saying:

6.click on id=viewns_Z7_I14A1CG0M8J010ARM8G5MR3084_:form:firstname... Failed:
Cannot read property 'root' of undefined
'foo' ended with 1 error(s)

In Firefox I get an error like:

6.click on id=viewns_Z7_I14A1CG0M8J010ARM8G5MR3084_:form:firstname... Failed:
this.playingFrameLocations[e] is undefined
'foo' ended with 1 error(s)

## To Reproduce

Try to use latest version of SIDE in any constructive way whatsoever.

## Expected behavior

I would at least expect to be able to run individual commands recorded in Selenium IDE.  I would also not expect to be forced into creating a new "project" or enter a starting URL.  I would expect it to work like the previous version did instead of not working like this version.

## Project file reproducing this issue (highly encouraged)

I'm pretty sure this happens regardless of the project?

Issues without a reproduction project are likely to stall.

## Environment

OS: Windows 10
Selenium IDE Version:  3.4.2
Selenium SIDE Runner Version:  No idea, I just installed the Selenium IDE from respective plugin store in each browser.
Please note that selenium-side-runner supports Node.js 8 - 10
-->
Node version: 
Browser:
Browser Version: Chrome Version 69.0.3497.100 (Official Build) (64-bit) / Firefox 62.0.3 (64-bit)

**Comment by corevo** [comment]
Our test projects that we run each day are working perfectly.  
More over the project's code of conduct

**Comment by apocalysque** [comment]
Sorry, disrespect wasn't my intent.  I suppose I should have been a little more clear instead of "lame".  IMO, it seems like this new "startup screen" or "welcome screen" or whatever it's called is hindering functionality/productivity of the IDE.  I'd prefer that creating and naming projects and tests and using startup URLs would be optional instead of forced on the user.  Most other applications I've used have a cancel or "don't show me this again" option for these types of situations.  And I don't see how forcing a startup URL helps.

I also tested this on a different page and voila, it works fine just like you said.  So, I've attached a reproducer that should show you the battle I'm fighting at the moment.

[foo.zip](https://github.com/SeleniumHQ/selenium-ide/files/2466212/foo.zip)

**Comment by tourdedave** [comment]
@apocalysque I want to make a distinction about the different topics in your issue. 1) being unable to record and playback in the application under test, 2) when the IDE is unsuccessful it fails with an unhelpful error, and 3) improvements to the UX of the IDE for productivity.

Based on the information you've provided, it looks like you were experiencing 1, 2, and 3. But I'll put 3 aside for now.

Unfortunately with the repro case you've provided I'm unable to confirm item 2 (e.g., `this.playingFrameLocations[e] is undefined` or `Cannot read property 'root' of undefined`) in either FF or Chrome. If you keep seeing these errors, please let us know, and provide more details if possible to see if we can confirm and find a fix.

Regarding item 1, the locators in the application you're testing are invalid. `:` is a reserved character for CSS pseudo-classes.

![image](https://user-images.githubusercontent.com/457137/46916724-08ed2180-cfc7-11e8-881a-2ee5b64e54f5.png)

The IDE records and attempts to use these even though they are invalid (e.g., it's valid according to the HTML spec, but we're using CSS to locate all elements and this is invalid according to the CSS spec). We are looking into potential enhancements to notify users of issues like this, rather than attempting to blindly try locators that won't work.

**Comment by tourdedave** [comment]
I've opened #452 to track the issue of recording invalid locators.

**Comment by tourdedave** [comment]
Okay, it turns out that while the locators aren't valid CSS, Selenium is able to work with them since escaping is handled further upstream. In the repro case provided the issue is that the elements are not on the page. It looks like the form option used in the test doesn't take you to the appropriate page when clicking `Next`. Here is an updated project which fixes that and demonstrates the test case working with the recorded locators.

[foo2.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/2477911/foo2.side.zip)
