### ISSUE TITLE
Selenium-side-runner minimum version on .side files

### ISSUE THREAD

**Issue by Yrds** [SeleniumHQ/selenium-ide#482]
## 🚀 Motion to appeal

First, I would like to thank for the advanced development, the community is growing rapidly too.

Is it possible to add the minimum version to the .side files to check when the tests are run through the selenium side runner?

## Motivation

I have a question about the minimum versions of selenium side-runner in .side files. For example, happen this week:

The developer ran the tests and failed, but on my machine and on the other developer the test runs fine. We found that the test was failing because the version was outdated, and the bug mentioned in # 466 had not yet been fixed

## Example

check that the selenium side-runner> "side-runner-min-ver" then run tests case the preposition is true, else not notify the user to upgrade.

**Comment by corevo** [comment]
Currently we check for version compatibility, only when things aren't backwards compatible, rather than forwards compatible.  
For example, if you've created a project using a newer version of the IDE than the runner installed, you will be notified to upgrade.  
But doing forward compatibility is difficult, since we may release a version of the runner that fixes an issue in `click`, that does not necessarily mean that we can't run the project file you are trying to run, it just means that there may be a bug.  
The way to deal with is, is either:
 - When facing a bug the user will manually check if he is running the latest version of the runner, and upgrade if necessary.
 - Notify the user if he is not using the latest version of the runner.

**Comment by Yrds** [comment]
Oh right, thanks for the clarification.
I will close this issue.
