### ISSUE TITLE
Can you use Select Window with the Window Title?

### ISSUE THREAD

**Issue by schunt1** [SeleniumHQ/selenium-ide#494]
I am able to use Select Window using the generated ID, but the Reference suggest that I should also be able to the window title. 

"Window locators provide different ways of specifying the window object: by title or by generated id"

I have tried using "title=window title" in the target, but that doesnt work.

**Comment by corevo** [comment]
We are planning changes to `select window` since the command is not working very well in accordance with WebDriver.  
Moreover the system of naming of `win_ser_2` and the likes is very hard to understand.  
I will make sure to post adequete information of the change, that being said selecting windows based on titles is not something that currently works, nor will work, but the new revised way of selecting windows will take care of that use-case, and I doubt you would need to relegate into doing so.
