### ISSUE TITLE
Selenium IDE should respect full base url with a path

### ISSUE THREAD

**Issue by cawoodm** [SeleniumHQ/selenium-ide#508]
If we use the command e.g. `open /login` and the base URL is `http://myserver.com` Selenium will open the URL `http://myserver.com/login` which is correct. However, if we use the base url `http://myserver.com/something` we would expect Selenium to open `http://myserver.com/something/login`. This does not work and Selenium IDE opens `http://myserver.com/login`.

Using `open login/` also does not work.

Justification: many websites are behind a reverse proxy and their root path `/` is mapped by the reverse proxy to `/something/`. When we need to test the website directly (internally bypassing the reverse proxy) we would need to append the `/something` part.

![image](https://user-images.githubusercontent.com/498834/49146780-2cfc8c00-f303-11e8-856b-5a49776729d4.png)

**Comment by Yrds** [comment]
Try to put "/" in the end of your base URL.

Like this:
[test.zip](https://github.com/SeleniumHQ/selenium-ide/files/2625309/test.zip)

**Comment by cawoodm** [comment]
Adding the `/` makes no difference:

![image](https://user-images.githubusercontent.com/498834/49274969-378d6180-f47a-11e8-96d7-efbc1a6ff986.png)

**Comment by corevo** [comment]
I've pushed a fix for it, but make sure to keep in mind two rules
 - if the target url starts with a `/` it will replace the entire path since `/` instructs the url to start from the root
 - if the base url ends with a `/` it will get treated as a directory, otherwise as a file

To make sure your use case works, make sure the base url is `http://myserver.com/something/` and the target url is `login` this will end up with `http://myserver.com/something/login`.
