### ISSUE TITLE
Why isn't base url on every test case?

### ISSUE THREAD

**Issue by Jongkeun** [SeleniumHQ/selenium-ide#513]
## 💬 Questions and Help

I'm curious why the base URL is only one by a project.
I want to manage the base URL by the test case.
Is there any certain reason?
Is that also the problem of independent?

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
The use case we envisioned was that you wanted to test a specific app with a project.  
This would allow us to assume that app has one endpoint, which would make it far easier to change the environment of that app, if you wanted to test against the staging version of it, only one place to change the url.  
Other than that a base url for each test case is not very useful, since it will only make a difference if you use it more than once, most test cases in our opinion use the `open` command only once, if that is the case, you can use an absolute url and change that, since regardless of wether it is a relative url using a test case basis base url or an absolute, you would still have to change it once for every test case.

**Comment by Jongkeun** [comment]
Oh, it sounds good. 
I got it. Thanks
