### ISSUE TITLE
Execute script should return properties of global variables on 'window' DOM

### ISSUE THREAD

**Issue by automagicmike** [SeleniumHQ/selenium-ide#527]
## 🐛 Bug Report

'Execute script' should return properties of global variables on browser 'window' DOM
Is there an issue / feature preventing 'execute script' from accessing global variables? 

This works OK on FF (64.0)  but fails on Chrome, Canary and Chromebook with
Cannot read property 'fn' of undefined 
- 'execute script' does not appear to have access to the windows object and global variables
e.g. window.myVar or myVar would return null

(Using Google Chrome (windows v17)  Selenium IDE v3.4.5.   )

## To Reproduce

Base URL: https://www.seleniumhq.org/ 
execute script | return (window.$.fn.jquery) | jqver
Note: returning document.title and  Math.PI  do work

Run attached script
[test1.zip](https://github.com/SeleniumHQ/selenium-ide/files/2722124/test1.zip)

## Expected behaviour

The jquery version (currently "3.1.0" ) is placed in the jqver variable.
This can be confirmed with verify or echo. 

## Project file reproducing this issue (highly encouraged)

Please provide a project file `.side` that reproduces this issue.

Issues without a reproduction project are likely to stall.

## Environment

FAILED:
OS:  Windows 10 pro
Selenium IDE Version:  3.4.5
Browser: Windows Google Chrome
Browser Version:  71.0.3578.98 (Official Build) (64-bit)

FAILED:
OS:  Windows 10 pro
Selenium IDE Version:  3.4.5
Browser: Windows Google Canary
Browser Version: 73.0.3659.0 (Official Build) canary (32-bit)

FAILED:
OS:  Chrome OS  71.03578.94 (Official Build) (64-bit)
Selenium IDE Version:  3.4.5
Browser: Google Chrome
Browser Version: 

PASSED:
OS:  Windows 10 pro
Selenium IDE Version:  3.4.5
Browser: Windows FireFox
Browser Version:  64.0 (64-bit) 

Selenium SIDE Runner Version:  Not using SIDE runner  
Node version:

**Comment by corevo** [comment]
This is due to Chrome, not having `window.eval` like in Firefox, rather we eval in the content script.

**Comment by automagicmike** [comment]
I called _window.eval('window.$.fn.jquery')_
from the console window in dev tools - and that worked.
If you can be a bit more specific about what's missing I'll raise a bug with the Chromium devteam.

**Comment by corevo** [comment]
Yes of course, the question is when calling `window.eval` what is window.  
In the console the window is the window under which the application is running, so when calling `window.$` you are calling the $ variable defined by the application.  
In WebExtensions, there is a global variable as well, called Sandbox, it works similarly to the window object, but a bit differently.  
So when you call `eval` in the extension, it actually evals the code in a different javascript context (a.k.a "window"), this way the extension doesn't interrupt normal application behavior.  
Now in Firefox, you can specify which window you want to eval in, so we specify the application's window, which is why you have $ defined, in Chrome we can't specify that, so we use the extension's window instead, in which your application's variables are not defined.  
If you look at this [mdn article](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Using_eval()_in_content_scripts), there is `eval` and `window.eval`, we want to use `window.eval` but in Chrome we only have `eval`.
I hope that clears things up a bit.  

Now from what I've seen since this has been asked before, most use cases require jQuery to be defined, we can define $ to be [document.querySelector](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector) and hopefully that would alleviate the issue a bit, until such time that a permanent fix can be implemented.

**Comment by automagicmike** [comment]
Thanks
This was not for jquery specifically, I'm only using that for demonstration purposes. 
Previously I found running a wide range of unit test to be often simpler and faster in Selenium IDE than other frameworks 
I need to test the keys/variables used by 3rd parties e.g. Google analytics, Liveperson etc
- check redirects and performance data and some simple unit tests
(In-browser regressions can run by (non technical) business users that can't install additional software / have low spec machines )

A dirty little hack which I'm not proud of is to ...
a) create a script element which creates a "p" tag with the innerHTML as the evaluated JavaScript return value
b) use a selenium "verify text" to confirm the value via the id.
sc = document.createElement("script"); sc.innerHTML= 'p=document.createElement("p"); p.id="id1"; d.innerHTML =' + window.$.fn.jquery + '; document.body,appendChild(d);',  document.body,appendChild(sc)

A "verify execute script" would save a line in the test.
Is that possible - if so I'll raise a feature request.
Updated side test below ...

[test1a.zip](https://github.com/SeleniumHQ/selenium-ide/files/2743183/test1a.zip)

Thanks Mike

**Comment by corevo** [comment]
Also some more information on the [behavior](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Content_script_environment).  
As you can see it says a content script can't access variables defined by the page script, luckily Firefox lets us `eval` things in the page context, but Chrome doesn't.

**Comment by toddtarsi** [comment]
I think this should be fine now since we aren't eval'ing anymore, but instead having a driver execute a script. (v4, not v3)
