### ISSUE TITLE
echo seems to fail (cause unknown)

### ISSUE THREAD

**Issue by p2635** [SeleniumHQ/selenium-ide#553]
## 🐛 Bug Report

When I do an echo command after closing a popup window, then selecting the main window again, the test fails.
![default](https://user-images.githubusercontent.com/4522927/51608453-70dccd80-1f0f-11e9-8794-c1ddcf67bfb3.png)

## To Reproduce

See SIDE file and try to run it.

## Expected behavior

echo works as normal and passes.

## Project file reproducing this issue (highly encouraged)

[echobug.zip](https://github.com/SeleniumHQ/selenium-ide/files/2787377/echobug.zip)

## Environment

OS: Windows 10
Selenium IDE Version:  3.5
Browser: Firefox
Browser Version: 64.0.2 (64 bit)

May need testing on Chrome.

**Comment by corevo** [comment]
We'll make the error clearer, we've made a change to the way `close` works, to be more similar to WebDriver, when calling `close` we will not return to the last selected window. Instead you have to specify it, while no window is specified no commands can work, use `select window` before calling `echo`.  
For the specific reason why `echo` doesn't work when no window is selected, is because you are able to print variables, and in order to do that we need a javascript vm, for that we use the target window.  
Regardless we need a better error message.

**Comment by corevo** [comment]
For now, we'll get `echo` working, it make sense to work even without a target window.

**Comment by corevo** [comment]
Closed in 7ed1472
