### ISSUE TITLE
Problema con ventanas y lineas comentadas

### ISSUE THREAD

**Issue by Maria874** [SeleniumHQ/selenium-ide#561]
## 🐛 Bug Report
Se presentó inconveniente con la nueva version 3.5.0 en donde al seleccionar una nueva ventana Selenium no la detecta. A su vez, también se presenta que al momento de colocar una linea en comentario Selenium la sigue tomando como si no estuviera comentada.

## To Reproduce

1. open URL   OK
2. Set window size 1366x728 OK
3. click link text = Inicio Fail
4. Select window handle=${win982}

Cuando se abre el sitio , carga automaticamente las dos ventanas dejando en foco una ventana donde no se cuentra el link text, anteriormente este comportamiento era transparente porque detectaba las ventanas, con la nueva versiòn al parecer no las detecta.

Siguente comportamiento:

1. open URL   OK
2. Set window size 1366x728 OK
3. // click link text = Inicio Fail
4. // Select window handle=${win982}

Selenium sigue parando la ejecución en la misma línea a pesar que esta comentariada.

## Expected behavior

Version anterior funcionaba correctamente en los 2 escenarios indicados anteriormente

## Project file reproducing this issue (highly encouraged)

El proyecto necesita vpn forticlient para su ejecución

## Environment

OS: 

-->
Browser: Chrome 
Browser Version: Versión 71.0.3578.98 (Build oficial) (64 bits)

**Comment by corevo** [comment]
Translation:
<details>
Problems with version 3.5.0 when you select a new window Selenium doesn’t detect it. Also when making a line in comment (I guess?) Selenium still takes it as if wasn’t commented. 

To Reproduce

open URL OK
Set window size 1366x728 OK
click link text = Inicio Fail
Select window handle=${win982}
Qhen the site is open it automatically loads both windows focusing a qindow where theres no link text. Before, this was  transparent because it detected the windows, but with the new version it doesnt.

next behavior:

open URL OK
Set window size 1366x728 OK
// click link text = Inicio Fail
// Select window handle=${win982}

Selenium stips execution in the same line even tho its commented

Expected behavior
The previous version worked fine with both scenarios 

Project file reproducing this issue (highly encouraged)

the project needs vpn forticlient to be exectued

Environment

OS: 
Browser: Chrome
Browser Version: Versión 71.0.3578.98 (Build oficial) (64 bits)
</details>

Anyway seems to be complaining about comments not working anymore, and executing even though they shouldn't,  I ran our comment test and it's working. Same goes for `select window`.

**Comment by tourdedave** [comment]
Closing this issue due to prolonged inactivity.
