### ISSUE TITLE
Is there a way to invoke selenium ide in an electron app?

### ISSUE THREAD

**Issue by lwp007** [SeleniumHQ/selenium-ide#579]
## 💬 Questions and Help
Is there a way to invoke selenium ide in an electron app? I am working on a test towards an electron app, and it is really a big work to write script, is there a way to record scripts using selenium ide? Thanks a lot!
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [SeleniumHQ IRC channel](https://webchat.freenode.net/)
- [SeleniumHQ Slack channel](https://seleniumhq.herokuapp.com/)
- The [Selenium Users](https://groups.google.com/forum/#!forum/selenium-users) google group

**Comment by corevo** [comment]
The solution would be to install Selenium IDE as an extension for your electron app, but it currently seems impossible according to https://github.com/electron/electron/issues/1498.  
I suggest talking to the people over at electron, because Selenium IDE requires an environment that can install WebExtensions.
