### ISSUE TITLE
Element Not Interactable Error

### ISSUE THREAD

**Issue by Rajagopalan-M** [SeleniumHQ/selenium-ide#611]
I recently started using this new Selenium IDE. I have been using the old selenium so far. I found this new selenium IDE perfectly waits for everything even for ajax call. But I think it's not waiting for element visibility. I have automated my website using this Selenium IDE, most of the parts are running properly, it throws the error element not intractable error at certain point, I think this error says that element is not visible(assuming from Firefox element not intractable error). If I resume my program from that point, it started running finely, so I guess element is taking few seconds to become visible, So Selenium IDE has to add Implicit wait for element visibility as well. 

And also I don't know how to increase the implicit wait in this selenium IDE, it default waits for 3000ms. How can I increase this time? 

And also will this selenium IDE allows me to save the result into a variable which I will use for next testcase as a prerequisite? 

And also I want to know whether we can generate any report at the end of the execution?

**Comment by tourdedave** [comment]
Please follow the issue template and provide all of the requested information in it (e.g., regarding the error you experienced).

If you think it's due to a timing issue, you can use an explicit wait command. See the `wait for` commands in the documentation ([link](https://www.seleniumhq.org/selenium-ide/docs/en/api/commands/#wait-for-element-visible)).

Regarding your other questions, please consider taking them to one of the places mentioned on [the project's help page](https://www.seleniumhq.org/selenium-ide/help/) (as this isn't a support forum -- it's for filing bugs found in the project).

**Comment by Rajagopalan-M** [comment]
@tourdedave Thank you very much.

**Comment by tourdedave** [comment]
You're welcome!
