### ISSUE TITLE
MacOS-SavingBug: Project can't be opened again after saving in macOS (with default settings)

### ISSUE THREAD

**Issue by easylite376** [SeleniumHQ/selenium-ide#682]
## 🐛 Bug Report

If  you save a file with default settings, it can't be opened again next time on MacOS. Problem is: It is saved as an `.txt` file. You have to manually change file type to `all types` and add `.side` manually.

## To Reproduce

1. Create Project
1. Hit Cmd+s or save
1. save file
1. try to open project again

## Expected behavior

The file is saved as an .side file, so it can be opened again on the next use.

## Environment

OS: OSX 10.14. 
Selenium IDE Version:  3.7 
Browser: Chrome
Browser Version: 74.0.3729.131 (64 Bit)

**Comment by tourdedave** [comment]
Unfortunately I'm unable to reproduce the issue locally. Can you try creating a new profile in Chrome, installing Selenium IDE there, and creating/saving a project to see if the issue persists?

As an interim workaround, you can cmd+i into the file to change the extension so you can open it in the IDE.

With the move to Electron this problem will go away, but that's not for quite some time since it's a large effort to get there. If we're unable track down the root cause of why Chrome sometimes saves the project this way, then we'll need to look into a safe way to load a JSON file with the wrong filetype.

**Comment by easylite376** [comment]
Okay, it is very strange. It is working with a new profile in chrome.

I just tested it on my windows machine and it also doesn't work there. I just can select between `Text Document` and `All Files`. I will look into my other extensions if I can find something.

**Comment by easylite376** [comment]
Okay found the problem. An addon called `Downloads Router` is scanning my downloads and is moving them automatically to subdirectories. It looks like, it is changing the selected filetype from `.side` to `.txt`. (It overwrote the menu point `.side-Filetype` with `Text document` completly.

**Comment by tourdedave** [comment]
Oh wow, nice find! Good to close?

**Comment by easylite376** [comment]
Yes good to close :) Thanks for your help :)

**Comment by tourdedave** [comment]
Great! You're welcome. Thanks for looking into things on your end.
