### ISSUE TITLE
Timeout that I set in suit settings is not taken into account

### ISSUE THREAD

**Issue by MaryQ** [SeleniumHQ/selenium-ide#699]
## 🐛 Bug Report
I set different values(such 5500) in 'Timeout (seconds)' field of 'Suite properties' in Selenium IDE and run my project which has click command with non existing element. As I exepect 'TimeoutError:' apears, but it appears after 30s in selenium ide and after 15s in command line.

## To Reproduce
1. Run 1.side project by clicking on 'Run all tests in suite' in selenium ide or by command selenium-side-runner 1.side
2. You will see following logs:
![image](https://user-images.githubusercontent.com/16049859/58080023-0553f580-7bbb-11e9-87c5-f41f524b2163.png)
![image](https://user-images.githubusercontent.com/16049859/58079951-dc336500-7bba-11e9-924f-2c050f2094a3.png)

## Project file reproducing this issue
[1.zip](https://github.com/SeleniumHQ/selenium-ide/files/3201469/1.zip)

## Environment
OS: Windows 10
Selenium IDE Version: 3.7.4
Selenium SIDE Runner Version: 3.7.4
Node version: npm: 6.7.0
Browser: Chrome

**Comment by corevo** [comment]
The suite timeout is how much time to wait for the test to complete before terminating the test run, so that it won't keep your CI running forever, set that to an amount that is high enough so that the test can complete under any circumstance, but low enough so that your CI won't clog if it doesn't.  

To change the waiting times for elements use `selenium-side-runner --timeout=30000`, I'm sorry for the confusion.

**Comment by MaryQ** [comment]
> To change the waiting times for elements use selenium-side-runner --timeout=30000, I'm sorry for the `confusion.
Is it possible to set this timeout in selenium ide?

**Comment by corevo** [comment]
Not atm
