### ISSUE TITLE
Type command not replacing value attribute on input field on Chrome & Safari when running with selenium-side-runner

### ISSUE THREAD

**Issue by akalidas** [SeleniumHQ/selenium-ide#708]
## 🐛 Bug Report
Currently, when trying to issue the type command via the selenium-side-runner, it does not replace the value attribute of the input field on both Chrome and Safari. It works perfectly well on Firefox.

## To Reproduce

Please run the attached .side file to simulate the issue on the "How much do you need?" text field.

## Expected behavior

Type command will replace the value of the input field on both Chrome and Safari similar to Firefox

## Project file reproducing this issue (highly encouraged)

I have attached a sample .side script that will simulate this issue on https://www.bettercash.com/

[Type_Command_Not_Working.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/3236166/Type_Command_Not_Working.side.zip)

## Environment

OS: OSX
Selenium IDE Version:  3.8.0
Selenium SIDE Runner Version:  3.8.0
Node version: v11.5.0
Browser: Chrome
Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)
Browser: Safari
Browser Version: Version 12.1.1 (14607.2.6.1.1)

**Comment by akalidas** [comment]
Hi @corevo, I was wondering if this issue is something that you have encountered before or maybe even something that I can look at to debug?

**Comment by jyeow90** [comment]
Having this issue as well. Any updates?

**Comment by Raths01** [comment]
Facing this issue as well. Instead of replacing, it just appends the text. Update on this would be really useful.

**Comment by tourdedave** [comment]
In the runner, the IDE's `type` command gets emitted as `element.clear()` and `element.sendKeys()`. When running the script the new value gets added in addition to the original value.

It looks like a bug in Selenium's `clear` command. Possibly because it's sending the wrong event (details available [here](https://github.com/SeleniumHQ/selenium/issues/1841)).

I'll look into a possible workaround.

**Comment by tourdedave** [comment]
Tracking for reference:

### Events in the IDE

<img width="1792" alt="events-ide" src="https://user-images.githubusercontent.com/457137/59249950-a79d5100-8c2e-11e9-8a01-273cb918cd1a.png">

### Events in the runner

<img width="1582" alt="events-runner" src="https://user-images.githubusercontent.com/457137/59249957-aa984180-8c2e-11e9-8eca-55b950f6c926.png">

**Comment by tourdedave** [comment]
The script works in Firefox. This ultimately looks like a bug in ChromeDriver. This will likely be resolved when the Chromium team finishes implementing the Actions API ([here's their open issue about it](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1897)).

As for workarounds, Instead of the `type` command you could use `executeScript` to clear the field and input text with JavaScript, or you could run the tests on Firefox for the time being.

**Comment by tourdedave** [comment]
Closing since this is a bug in ChromeDriver.
