### ISSUE TITLE
Relationship to SideEx? 

### ISSUE THREAD

**Issue by winterstein** [SeleniumHQ/selenium-ide#75]
Hello, and firstly thank you for your time in making this.

I have a couple of questions on how this project relates to SideEx:

1. The readme acknowledges that SideEx has been used as a starting point. Is that link going to continue (i.e. this project will draw updates from SideEx, e.g. in the way that say Ubuntu draws from Debian)? Or will the two projects diverge?

2. How do the two projects differ? They look quite similar today, so perhaps a better question is how do their goals and roadmaps differ?

NB: I've posted this as an issue, as I think it'd be helpful to update the readme to include this material.

All the best,
 - Daniel

**Comment by Zaanmedia** [comment]
Well they are not the only party out there... there is also something like Katalon that seems quite popular and they also forked the SideeX project as a starting point and created the Katalon automation recorder true a hackaton.

I think all the party's having a different feature/road-map for the product.

Anyway i guess both have their advantages. I wish they shared the same format for suites/cases and also had the feature to cross import and run test suites between the recorders.

Anyway will keep an eye out on those three projects in particular Selenium IDE, SideeX and Katalon since they seems to be most active these days.

**Comment by idefix1** [comment]
Note that Katalon is not open-source. But there is also the [Kantu Selenium IDE](https://chrome.google.com/webstore/detail/kantu-browser-automation/gcbalfbdmfieckjlnblleoemohcganoc?hl=en) which _is_ open-source ([github repo](https://github.com/A9T9/Kantu-for-Chrome)) but _not_ based on SideEx.

**Comment by corevo** [comment]
Hey all, sorry for the late response.  
1. Currently we do not plan on pulling updates from SideeX, but if something worthwhile, or requested by the community will asked then that may change.  
2. Functionality they do look very similar to this day, I can't speak for SideeX's roadmap, but our plan for the time is to add the ability to run test suites from CI, and is currently being worked on, later we plan on adding support for extending the IDE.
  
I have had plans to update the README, I'll keep this open till I do.

**Comment by corevo** [comment]
Since SideeX has not been actively maintained for the past 6 months I am closing this issue.  
As well as the fact that SideeX do not share a roadmap, the only answer I can give at this moment is that the projects have diverged.
