### ISSUE TITLE
Want the ability to run test on an existing tab/window instead of opening a new one every time

### ISSUE THREAD

**Issue by GavintheAmateur** [SeleniumHQ/selenium-ide#788]
## 🚀 Feature Proposal
Want the ability to run test on an existing tab/window instead of opening a new one every time
## Motivation
want one script used on a set of similar pages, and want to use them when a page has been opened on the opened page. that would be much more convenient. This used to be how it worked in selenium IDE 2.9.*, but it's too old to be supported by current browsers.

**Comment by corevo** [comment]
Since Selenium IDE will be moving to an electron app in the future, running in an open tab in a browser will be impossible, adding this feature now would be a disservice to users when the IDE as an extension will retire (once the IDE will become an electron app, the extension will retire).

Instead, if you can explain what is the flow you're trying to achieve? maybe we can account for that in the IDE in another way.

As a side note, the WebDriver protocol requires opening a new tab, and can't be used with an already existing tab (due to security reasons), we can't change that behavior.

**Comment by darkartswizard** [comment]
I strongly disagree.

ALL of my framework designs support hooking into an existing browser
because UNIT TESTING.

Might as well tell the automation world there is something UFT can do with
VBscript that is impossible in Selenium with Java.

Paul Grossman

**Comment by diemol** [comment]
Well, is the Selenium WebDriver the tool to use for Unit testing?

**Comment by corevo** [comment]
@darkartswizard I think that by guiding users to re-use the environment from a previous test to the next you open the door for many flaky tests (e.g. tests that rely on the previous test to succeed in order to run).

Also, if you don't mind how do you hook into an existing browser? do you boot up the browser with the remote debugger on at all times? WebDriver is built with that point in mind, to avoid by accident a situation where a rogue software would take over the user's browser. (I'm asking to make sure there is no security issue here)

Lastly this is not the right forum for the question of wether WebDriver should or shouldn't hook into an existing browser session, if you'd like to open that for discussion you should head to [w3c/webdriver](https://github.com/w3c/webdriver), again not writing this because of my personal preference, but because this is really not the place, and this decision can be changed by browser vendors rather than the Selenium team.

**Comment by darkartswizard** [comment]
No.

The unit testing is when I have 50+ statements in an existing test and need
to add and debug one more new bit of functionality.

I have to run my full test from the beginning to get to the point that the
browser is displaying the new object to interact. And this might include
regenerating all new data, just to see if some new value was misspelled, or
is case sensitive, or even  appears in a new dropdown list.

In my frameworks I design to re-execute the last statement against an
element, my new functionality, against the last open browser, which I
intentionally leave open at the end of a  for just this purpose.

I learned to do this since my Winrunner days in 2001 where I could actually
run to a stop point, mod my code, drag the execution arrow back to a few
lines, and run from there to re-test. When my support libs were 1000+ lines
of code it was absolutely brilliant.

To assume that every new LOC will always come it at under line 10, and to
debug it will take a few seconds of re-execution is severely short-sighted.
It assumes a very short automation project. Mine last for years.

I’m sorry I feel very strongly about this.  I occasionally do gap analysis
on inherited automation framework designs by junior developers.  They never
stay on a project long enough to experience this, or never code a solution
to work more efficiently and avoid the increasing time sync technical debt.

Paul

**Comment by corevo** [comment]
I don't disagree with your point, I disagree with the method.

In the IDE, in case you have a failing command (statement), we have the tools to cope with that, we do not expect anyone to sit again for minutes or hours to get to the same point just to test it for a second, you can either set a debugger or set the stop on exceptions toggle, this will allow you to re-execute the failing command until it is fixed (you are free to tweak the script while debugging).

Another tool we give the users is to re-run from a line, for example if they ran a test from line 1-7 and 8 failed, they can stop, fix the test and continue from line 8, but **they must continue on the browser session that they started with** (the browser that the IDE created on line 1).

There is a very important distinction, we allow users to continue a test from the middle multiple times, so long as it is on a browser initialized by the IDE, for security reasons, all the problems you've described can be accounted for and taken care of today within the IDE, plus some security concerns.

Removing security layers for the sole purpose of re-execution, is unnecessary and dangerous.

What isn't possible on the IDE is to open a browser manually and connect to it, but a third workaround (that I wouldn't recommend), is to open a browser via the IDE, and setting a breakpoint on the first line, this would allow you to manually set the environment for the rest of the script.

On a more personal note, I wouldn't test 50+ things in a single test, the results of such tests would be very difficult to decipher (which one of the 50+ assertions failed, and what of the 50+ actions could've caused it), maybe on an e2e test, but definitely not a unit one (I would also try to unit test my webpages without a browser if possible, either by testing the logic on its own, or component based testing with jsdom or enzyme).

**Comment by darkartswizard** [comment]
Maybe I misunderstood what the poster was requesting. Choosing ANY open
browser is not feasible. It sounds like the functionality I’m describing is
already in place and I’ll spend some time with the latest build to check it
out.

To be clear I’m not testing 50+ items in one test. I’m describing an
end-to-end test where 49 actions are simple navigation and population to
get to the validation point.

For example: Let’s say we just completed a Happy Path test to purchase a
product.

Next we might want to validate with a declined credit card account to
display  “Sorry but your credit card has been Declined” after the card
transaction. We would simply replicate the Happy Path test and change the
final validation step.

The 50+ steps to generate that message might be to:
create a new user account,
search for a product that has inventory,
add the product to the shopping cart,
proceed to checkout,
add a new credit card,
enter the billing address,
enter the shipping address,
and process the transaction.

Let’s say at that point “Sorry, but your credit card has been declined”
appears and the validation step fails - because the added comma “, ” and
lowercase “d” did not match.

It should be easy to change the expected data in that final step and
re-execute the validation line against the open browser window taking
milliseconds - assuming the browser was left open at the end of the last
run - without having to run the entire sequence again which might take
minutes.

That said, there are 50+ validations being performed in this end to end run
regardless: Each element exists, and is enabled, from Login to Check out.
But that’s by default.

Paul

**Comment by corevo** [comment]
I'm glad we've come to an understanding.
