### ISSUE TITLE
how to asset if item on tab selected  

### ISSUE THREAD

**Issue by minaairsupport** [SeleniumHQ/selenium-ide#830]
I keep looking for this for days and cant find anything 
all I need to assert against `aria-selected=true'`
or something in css

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
