### ISSUE TITLE
[Question] Hidden inputfields / dropzone?

### ISSUE THREAD

**Issue by pgroot91** [SeleniumHQ/selenium-ide#87]
Hallo All,

This is not really related to a bug! I'm trying to find a clear awnser for my problem. Is it possible to somehow target hidden inputfield or the dropzone to upload a file only using the Selenium IDE. 

Example: http://www.dropzonejs.com/examples/simple.html

When i try to target the hidden input field:
**[error] Element is not currently interactable and may not be manipulated**

Tried to find some awnsers on the internet and there is not directly a clear awnser to this problem or a way to manipulate that allows us to upload some files. Any ideas?

**Comment by corevo** [comment]
This is intended Selenium error that originates [here](https://github.com/SeleniumHQ/selenium/blob/ceaf3da79542024becdda5953059dfbb96fb3a90/javascript/atoms/action.js#L54)  
If an element is not visible it shouldn't be interactable, you can try to eval something to turn that element visible.

**Comment by pgroot91** [comment]
I understand but what is the prefered solutions to test file uploads then? Just not at all and take that part for granted?

**Comment by corevo** [comment]
Either you eval some javascript beforehand to make the element visible, or have a test version of the webpage where it is visible.  
It just not intended to work, it's as if we wanted to make onClick work on disabled buttons.
<br />
Also for best practice I would recommend not [hiding](https://www.w3.org/WAI/tutorials/fundamentals/hiding/) any element the user can interact with, since blind users won't be able to use it (as screen readers won't acknowledge it's existence).  
You might want to address this issue by having the element be positioned absolutely offscreen.
