### ISSUE TITLE
[Variables] Selenium IDE

### ISSUE THREAD

**Issue by pgroot91** [SeleniumHQ/selenium-ide#88]
In the old situation/test cases from the old IDE we used one test case that we always put as a start of our test suite and those variables could be used by all the following test cases inline. I'm not sure if you were able to run multiple suites at once. 

But my ideal solution the variables are usable and stored/available for all test suites and cases.

**Comment by corevo** [comment]
That can not be the case, although in Selenium IDE test cases are ran one by one in a synchronized fashion, we are actively working on exporting Selenium IDE projects to webdriver code where it will be ran in parallel.  
Thus you can't rely on a test case to be ran before you, and use it's variables.  
And since test cases will be ran independently in webdriver, they can't share variables between them, you would have to re-evaluate any or all variables before each test.

**Comment by manikumary** [comment]
Yes,  I agree with pgroot91.In  old selenium IDE  variables are possible and can be re-used with other scripts. This feature needed in new ide as well.

**Comment by olds97lss** [comment]
I do the same. In many scripts, I store the data from a field as the script runs, then in the next script, I use that variable as well.

**Comment by corevo** [comment]
We have the current resolution concerning variable sharing and scoping:  
![image](https://user-images.githubusercontent.com/888886/42819149-601b9662-89db-11e8-8108-5b66d742dd92.png)
Selecting `Persist session` will result in the behavior @pgroot91 explains, just as a heads up, it is **not recommended** because it may create bugs that are difficult to debug.  
Also unless `Run in parallel` is selected you can freely re-order test cases as you see fit.  
Note that persisting the session and running is parallel is not possible, because parallel means that there will be more than one session.
