### ISSUE TITLE
Dependancies in extensions

### ISSUE THREAD

**Issue by peter-kehl** [SeleniumHQ/selenium-ide#99]
Hi Tomer @corevo and Doron @zavelevsky,

Good that you're intending to support extensions to new Selenium IDE (#9).

@SeLite provided 14 extensions (to old IDE). Here's a takeaway:
* *Registration* by pull, but semi-active.
By pull: Extensions provide a special manifest. It gets noticed and get pulled and run by Selenium IDE.
Semi-active: Manifest is a .js rather than .json. That allows them to run adaptation logic.
Alternatively, extensions could register themselves by runtime.sendMessage(). But they'd still need to get pulled by IDE.
* *Dependancies*
We developers aim to leverage existing functionality. And we add more value. To help extending IDE add-ons - both @SeLite ones and from other developers - I implemented dependancy sequencing.
See http://selite.github.io/ExtensionSequencer (and http://selite.github.io/ComponentsDependants).

You may benefit from new API https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts.

Please, support dependancies.

**Comment by corevo** [comment]
We have come up with a similar solution,  
Extensions will register using external messaging, but they will not send logic to the IDE, not to be ran in background nor content script level.  
Browser providers are working very hard on user privacy and security, and we wanna stay in line with their recommendations and requirements.  
Thus our solution is to register capabilities (via JSON), for example extra commands, and the IDE will notify the extension when it is it's time to execute that logic, it does impose a lot of constraints on plugins, and some, such as Samit's Flow control will be included in the IDE because it has immense implication on the playback logic.

**Comment by corevo** [comment]
Closing since the [plugin API](https://github.com/SeleniumHQ/selenium-ide/wiki/Getting-Started-with-Plugins) is live.  
Any issue concerning the current implementation should have it's own ticket.
