### ISSUE TITLE
About firefox packaging: How to solve this error?

### ISSUE THREAD

**Issue by OrangeManDavid** [SeleniumHQ/selenium-ide#992]
****@ubuntu:~/****/workspace/SeleniumHQ/selenium-ide/packages/selenium-ide$ npm run-script build-firefox 
> selenium-ide-extension@3.17.0 build-firefox /home/****/workspace/SeleniumHQ/selenium-ide/packages/selenium-ide
> web-ext sign -s build -a dist --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --id=$(cat ../../.web-extension-id)

sh: 1: web-ext: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! selenium-ide-extension@3.17.0 build-firefox: `web-ext sign -s build -a dist --api-key=$AMO_JWT_ISSUER --api-secret=$AMO_JWT_SECRET --id=$(cat ../../.web-extension-id)`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the selenium-ide-extension@3.17.0 build-firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/****/.npm/_logs/2020-03-25T21_54_04_999Z-debug.log
****@ubuntu:~/****/workspace/SeleniumHQ/selenium-ide/packages/selenium-ide$ 

Thank U!

**Comment by corevo** [comment]
Hey, we've noticed you've filed an issue without filling out the template, we are receiving multiple tickets a day, and these templates are in place to help us manage the issue and provide solutions faster.  

As a result we're closing this issue, please resubmit the [issue following the template](https://github.com/SeleniumHQ/selenium-ide/issues/new/choose) and we'll make sure to look at it.

In addition to that in order to build the extension, run `yarn build` not `npm run-script build-firefox`, please follow the build instructions in the README.
