### ISSUE TITLE
'Test '' has a problem: n.value is undefined' error when exporting .side file to Java JUnit 

### ISSUE THREAD

**Issue by fedrocca** [SeleniumHQ/selenium-ide#999]
## 🐛 Bug Report

When trying to export my .side file to Java JUnit, the following error is displayed:

Test '_test case name_' has a problem: n.value is undefined

## To Reproduce
Issue can be reproduced by trying to export the attached Test Suite.

## Expected behavior
JUnit file is exported with the Test Suite.

## Project file reproducing this issue (highly encouraged)
[Dummy.side.zip](https://github.com/SeleniumHQ/selenium-ide/files/4415761/Dummy.side.zip)

## Environment

OS: macOS Catalina 10.15.3 - 
Selenium IDE Version:  3.17.0
Node version: 13.8.0

Browser: Firefox 
Browser Version: 74.0 (64 bit)

**Comment by varunblaze** [comment]
I am also facing this problem.

**Comment by tourdedave** [comment]
It's likely because of a command with an invalid entry (e.g., specifying a
value when the command doesn't accept one).

In the example you provided there are click commands that specify both a
target and a value -- but the command only accepts a target. You can move
the value entry into the description field and the export will work.


Cheers,
Dave H

**Comment by varunblaze** [comment]
Thanks Dave. Your suggestion helped me to resolve the problem.

**Comment by tourdedave** [comment]
Great!
